(Dialog pin_dialog
    (Components
        (SubLayout                      main_layout)
        (SubLayout                      hole_layout)
    )

    (Resources
        (.Label                         "Dowel Pin Fastener Definition")
        (.StartLocation                 3)
        (.Resizeable                    False)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.SystemMenuButton              True)
        (.TitleBarImage                 "buw_titlebar.png")
        (.Layout
            (Grid (Rows 1) (Cols 1 1)
                main_layout
                hole_layout
            )
        )
    )
)

(Layout main_layout
    (Components
        (SubLayout                      component_layout)
        (SubLayout                      expand_layout)
        (SubLayout                      expand_preview_layout)
        (SubLayout                      preview_layout)
        (SubLayout                      footer_layout)
    )

    (Resources
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 0 1 1) (Cols 1)
                (Grid (Rows 0) (Cols 1 1)
                    component_layout
                    expand_layout
                )
                expand_preview_layout
                preview_layout
                footer_layout
            )
        )
    )
)

(Layout component_layout
    (Components
        (SubLayout                      standard_layout)
        (SubLayout                      pin_layout)
        (SubLayout                      asm_layout)
    )

    (Resources
        (.Mapped                        False)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.Alignment                     1)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1 1) (Cols 1)
                standard_layout
                pin_layout
                asm_layout
            )
        )
    )
)

(Layout standard_layout
    (Components
        (Label                          standard_txt)
        (OptionMenu                     standard_combo)
        (CheckButton                    standard_dummy_check)
    )

    (Resources
        (standard_txt.Label             "Catalog")
        (standard_txt.Columns           6)
        (standard_txt.AttachLeft        True)
        (standard_txt.Alignment         1)
        (standard_txt.TopOffset         0)
        (standard_txt.BottomOffset      0)
        (standard_txt.LeftOffset        0)
        (standard_txt.RightOffset       0)
        (standard_txt.FontStyle         8)
        (standard_combo.Columns         20)
        (standard_combo.Names           "def1")
        (standard_combo.Labels          "-")
        (standard_combo.MinColumns      0)
        (standard_combo.TopOffset       0)
        (standard_combo.BottomOffset    0)
        (standard_combo.LeftOffset      0)
        (standard_combo.RightOffset     0)
        (standard_combo.MinDouble       0.000000)
        (standard_dummy_check.Visible   False)
        (standard_dummy_check.Mapped    True)
        (standard_dummy_check.AttachLeft True)
        (standard_dummy_check.TopOffset 0)
        (standard_dummy_check.BottomOffset 0)
        (standard_dummy_check.LeftOffset 0)
        (standard_dummy_check.RightOffset 0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     16)
        (.BottomOffset                  10)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1) (Cols 0 0 1)
                standard_txt
                standard_dummy_check
                standard_combo
            )
        )
    )
)

(Layout pin_layout
    (Components
        (OptionMenu                     pintype_comboex)
        (Separator                      pin_separator)
        (Label                          pin_txt)
        (CheckButton                    pin_check)
        (SubLayout                      pin_dxl_layout)
        (Label                          t2_txt)
        (SpinBox                        t2_spin)
        (Label                          dummy1)
        (CheckButton                    dummy2)
    )

    (Resources
        (pintype_comboex.Names          "def1")
        (pintype_comboex.Labels         "-")
        (pintype_comboex.ItemImage      "32x32.png")
        (pintype_comboex.MinColumns     15)
        (pintype_comboex.TopOffset      0)
        (pintype_comboex.BottomOffset   0)
        (pintype_comboex.LeftOffset     0)
        (pintype_comboex.RightOffset    0)
        (pintype_comboex.MaxColumns     15)
        (pin_separator.TopOffset        0)
        (pin_separator.BottomOffset     10)
        (pin_separator.LeftOffset       0)
        (pin_separator.RightOffset      0)
        (pin_txt.Label                  "Dowel Pin")
        (pin_txt.Columns                6)
        (pin_txt.AttachLeft             True)
        (pin_txt.AttachRight            True)
        (pin_txt.Alignment              1)
        (pin_txt.TopOffset              0)
        (pin_txt.BottomOffset           0)
        (pin_txt.LeftOffset             0)
        (pin_txt.RightOffset            0)
        (pin_txt.FontStyle              8)
        (pin_check.Visible              False)
        (pin_check.Mapped               True)
        (pin_check.AttachRight          True)
        (pin_check.TopOffset            0)
        (pin_check.BottomOffset         0)
        (pin_check.LeftOffset           0)
        (pin_check.RightOffset          0)
        (t2_txt.Label                   "Depth")
        (t2_txt.AttachLeft              True)
        (t2_txt.AttachRight             True)
        (t2_txt.Alignment               1)
        (t2_txt.TopOffset               5)
        (t2_txt.BottomOffset            0)
        (t2_txt.LeftOffset              0)
        (t2_txt.RightOffset             2)
        (t2_txt.FontStyle               8)
        (t2_spin.Columns                4)
        (t2_spin.AttachLeft             True)
        (t2_spin.AttachTop              True)
        (t2_spin.AttachBottom           True)
        (t2_spin.TopOffset              5)
        (t2_spin.BottomOffset           0)
        (t2_spin.LeftOffset             0)
        (t2_spin.RightOffset            0)
        (t2_spin.InputType              3)
        (t2_spin.Digits                 2)
        (dummy1.Columns                 6)
        (dummy1.AttachLeft              True)
        (dummy1.Alignment               1)
        (dummy1.TopOffset               0)
        (dummy1.BottomOffset            0)
        (dummy1.LeftOffset              0)
        (dummy1.RightOffset             0)
        (dummy1.FontStyle               8)
        (dummy2.Visible                 False)
        (dummy2.Mapped                  True)
        (dummy2.AttachRight             True)
        (dummy2.TopOffset               0)
        (dummy2.BottomOffset            0)
        (dummy2.LeftOffset              0)
        (dummy2.RightOffset             0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                pin_separator
                (Grid (Rows 0 0 0) (Cols 0 0 1)
                    pin_txt
                    pin_check
                    pintype_comboex
                    dummy1
                    dummy2
                    pin_dxl_layout
                    t2_txt
                    (Pos 3 3)
                    t2_spin
                )
            )
        )
    )
)

(Layout pin_dxl_layout
    (Components
        (OptionMenu                     durchmesser_combo)
        (PushButton                     measurediameter_button)
        (Label                          pin_x_txt)
        (OptionMenu                     laenge_combo)
    )

    (Resources
        (durchmesser_combo.Columns      5)
        (durchmesser_combo.TopOffset    0)
        (durchmesser_combo.BottomOffset 0)
        (durchmesser_combo.LeftOffset   0)
        (durchmesser_combo.RightOffset  0)
        (measurediameter_button.Bitmap  "ifx_pin_measurediameter.png")
        (measurediameter_button.HelpText "Measure a diameter")
        (measurediameter_button.ButtonStyle 2)
        (measurediameter_button.Alignment 2)
        (measurediameter_button.TopOffset 0)
        (measurediameter_button.BottomOffset 0)
        (measurediameter_button.LeftOffset 6)
        (measurediameter_button.RightOffset 6)
        (pin_x_txt.Label                "x")
        (pin_x_txt.TopOffset            0)
        (pin_x_txt.BottomOffset         0)
        (pin_x_txt.LeftOffset           3)
        (pin_x_txt.RightOffset          5)
        (laenge_combo.Columns           4)
        (laenge_combo.TopOffset         0)
        (laenge_combo.BottomOffset      0)
        (laenge_combo.LeftOffset        0)
        (laenge_combo.RightOffset       0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     10)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1 0 0 1)
                durchmesser_combo
                measurediameter_button
                pin_x_txt
                laenge_combo
            )
        )
    )
)

(Layout asm_layout
    (Components
        (Label                          asm_txt)
        (CheckButton                    asm_dummy_check)
        (OptionMenu                     asm_comboex)
        (Separator                      Separator12)
    )

    (Resources
        (asm_txt.Label                  "Assemble")
        (asm_txt.Columns                6)
        (asm_txt.AttachLeft             True)
        (asm_txt.Alignment              1)
        (asm_txt.TopOffset              0)
        (asm_txt.BottomOffset           0)
        (asm_txt.LeftOffset             0)
        (asm_txt.RightOffset            0)
        (asm_txt.FontStyle              8)
        (asm_dummy_check.Visible        False)
        (asm_dummy_check.Mapped         True)
        (asm_dummy_check.AttachLeft     True)
        (asm_dummy_check.TopOffset      0)
        (asm_dummy_check.BottomOffset   0)
        (asm_dummy_check.LeftOffset     0)
        (asm_dummy_check.RightOffset    0)
        (asm_comboex.HelpText           "Add fastener to selected assembly.")
        (asm_comboex.Names              "def1")
        (asm_comboex.Labels             "-")
        (asm_comboex.MinColumns         0)
        (asm_comboex.TopOffset          0)
        (asm_comboex.BottomOffset       0)
        (asm_comboex.LeftOffset         0)
        (asm_comboex.RightOffset        0)
        (asm_comboex.MinDouble          0.000000)
        (Separator12.AttachTop          True)
        (Separator12.TopOffset          10)
        (Separator12.BottomOffset       10)
        (Separator12.LeftOffset         0)
        (Separator12.RightOffset        0)
        (.Visible                       False)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                Separator12
                (Grid (Rows 0) (Cols 0 0 1)
                    asm_txt
                    asm_dummy_check
                    asm_comboex
                )
            )
        )
    )
)

(Layout expand_layout
    (Components
        (PushButton                     show_hide_holelayout)
        (Separator                      Separator4)
    )

    (Resources
        (show_hide_holelayout.Bitmap    "UI ToolBar right image")
        (show_hide_holelayout.HelpText  "Show/Hide Hole Layout")
        (show_hide_holelayout.ButtonStyle 3)
        (show_hide_holelayout.TopOffset 0)
        (show_hide_holelayout.BottomOffset 0)
        (show_hide_holelayout.LeftOffset 0)
        (show_hide_holelayout.RightOffset 0)
        (show_hide_holelayout.FontStyle 8)
        (Separator4.Orientation         True)
        (Separator4.Mapped              True)
        (Separator4.AttachTop           True)
        (Separator4.AttachBottom        True)
        (Separator4.TopOffset           10)
        (Separator4.BottomOffset        0)
        (Separator4.LeftOffset          0)
        (Separator4.RightOffset         0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.Alignment                     1)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                show_hide_holelayout
                Separator4
            )
        )
    )
)

(Layout expand_preview_layout
    (Components
        (PushButton                     show_hide_preview_layout)
        (Label                          preview_layout_txt)
        (Separator                      Separator5)
    )

    (Resources
        (show_hide_preview_layout.Bitmap "UI ToolBar up image")
        (show_hide_preview_layout.ButtonStyle 3)
        (show_hide_preview_layout.AttachLeft True)
        (show_hide_preview_layout.TopOffset 10)
        (show_hide_preview_layout.BottomOffset 10)
        (show_hide_preview_layout.LeftOffset 10)
        (show_hide_preview_layout.RightOffset 10)
        (show_hide_preview_layout.FontStyle 8)
        (preview_layout_txt.Label       "2D Preview")
        (preview_layout_txt.AttachLeft  True)
        (preview_layout_txt.TopOffset   0)
        (preview_layout_txt.BottomOffset 0)
        (preview_layout_txt.LeftOffset  0)
        (preview_layout_txt.RightOffset 10)
        (preview_layout_txt.FontStyle   8)
        (Separator5.Mapped              True)
        (Separator5.AttachTop           True)
        (Separator5.AttachBottom        True)
        (Separator5.TopOffset           10)
        (Separator5.BottomOffset        10)
        (Separator5.LeftOffset          0)
        (Separator5.RightOffset         10)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 0 0 1)
                show_hide_preview_layout
                preview_layout_txt
                Separator5
            )
        )
    )
)

(Layout preview_layout
    (Components
        (DrawingArea                    preview_2d)
    )

    (Resources
        (preview_2d.Decorated           False)
        (preview_2d.DrawingWidth        200)
        (preview_2d.DrawingHeight       215)
        (preview_2d.BackgroundColor     255)
        (preview_2d.TopOffset           10)
        (preview_2d.BottomOffset        10)
        (preview_2d.LeftOffset          10)
        (preview_2d.RightOffset         10)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1)
                preview_2d
            )
        )
    )
)


(Layout footer_layout
    (Components
        (PushButton                     pb_Cancel)
        (PushButton                     pb_OK)
        (CheckButton                    preview_check)
        (Separator                      Separator2)
        (Separator                      Separator3)
    )

    (Resources
        (pb_Cancel.Label                "Cancel")
        (pb_Cancel.Columns              5)
        (pb_Cancel.ButtonStyle          2)
        (pb_Cancel.AttachRight          True)
        (pb_Cancel.Alignment            1)
        (pb_Cancel.TopOffset            10)
        (pb_Cancel.BottomOffset         10)
        (pb_Cancel.LeftOffset           0)
        (pb_Cancel.RightOffset          10)
        (pb_OK.Label                    "OK")
        (pb_OK.Columns                  5)
        (pb_OK.ButtonStyle              2)
        (pb_OK.AttachRight              True)
        (pb_OK.TopOffset                10)
        (pb_OK.BottomOffset             10)
        (pb_OK.LeftOffset               0)
        (pb_OK.RightOffset              8)
        (preview_check.Label            "Preview")
        (preview_check.ButtonStyle      2)
        (preview_check.AttachLeft       True)
        (preview_check.TopOffset        10)
        (preview_check.BottomOffset     10)
        (preview_check.LeftOffset       10)
        (preview_check.RightOffset      0)
        (Separator2.AttachBottom        True)
        (Separator2.TopOffset           0)
        (Separator2.BottomOffset        0)
        (Separator2.LeftOffset          0)
        (Separator2.RightOffset         0)
        (Separator3.Visible             False)
        (Separator3.Orientation         True)
        (Separator3.TopOffset           10)
        (Separator3.BottomOffset        10)
        (Separator3.LeftOffset          8)
        (Separator3.RightOffset         8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                Separator2
                (Grid (Rows 1) (Cols 1 1 0 0)
                    preview_check
                    Separator3
                    pb_OK
                    pb_Cancel
                )
            )
        )
    )
)

(Layout hole_layout
    (Components
        (SubLayout                      holetype1_layout)
        (SubLayout                      holetype2_layout)
        (SubLayout                      footer2_layout)
    )

    (Resources
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1 1) (Cols 1)
                holetype1_layout
                holetype2_layout
                footer2_layout
            )
        )
    )
)

(Layout holetype1_layout
    (Components
        (CheckButton                    holetype1_check)
        (SubLayout                      holetype1_data_layout)
        (Separator                      Separator1)
    )

    (Resources
        (holetype1_check.Label          "Top Bore")
        (holetype1_check.AttachLeft     True)
        (holetype1_check.AttachRight    True)
        (holetype1_check.AttachTop      True)
        (holetype1_check.AttachBottom   True)
        (holetype1_check.TopOffset      0)
        (holetype1_check.BottomOffset   0)
        (holetype1_check.LeftOffset     0)
        (holetype1_check.RightOffset    0)
        (holetype1_check.FontStyle      8)
        (Separator1.TopOffset           10)
        (Separator1.BottomOffset        0)
        (Separator1.LeftOffset          0)
        (Separator1.RightOffset         0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0 1) (Cols 1)
                holetype1_check
                holetype1_data_layout
                Separator1
            )
        )
    )
)

(Layout holetype1_data_layout
    (Components
        (SpinBox                        t1_spin)
        (Label                          holetype1_txt)
        (OptionMenu                     holetype1_om)
        (Label                          d1_txt)
        (InputPanel                     d1_edit)
        (Label                          bt1_txt)
        (SpinBox                        bt1_spin)
        (Label                          bdm1_txt)
        (SpinBox                        bdm1_spin)
        (Label                          tol1_txt)
        (OptionMenu                     tol1_combo)
        (Label                          tolupper1_txt)
        (InputPanel                     tolupper1_edit)
        (Label                          tollower1_txt)
        (InputPanel                     tollower1_edit)
    )

    (Resources
        (t1_spin.Visible                False)
        (t1_spin.Columns                4)
        (t1_spin.Mapped                 True)
        (t1_spin.AttachLeft             True)
        (t1_spin.AttachRight            True)
        (t1_spin.AttachTop              True)
        (t1_spin.AttachBottom           True)
        (t1_spin.TopOffset              5)
        (t1_spin.BottomOffset           0)
        (t1_spin.LeftOffset             2)
        (t1_spin.RightOffset            0)
        (t1_spin.InputType              3)
        (t1_spin.Digits                 2)
        (holetype1_txt.Label            "Hole Type")
        (holetype1_txt.AttachLeft       True)
        (holetype1_txt.AttachTop        True)
        (holetype1_txt.Alignment        0)
        (holetype1_txt.TopOffset        0)
        (holetype1_txt.BottomOffset     5)
        (holetype1_txt.LeftOffset       0)
        (holetype1_txt.RightOffset      0)
        (holetype1_txt.FontStyle        8)
        (holetype1_om.Columns           8)
        (holetype1_om.VisibleRows       3)
        (holetype1_om.Names             "DURCH_1"
                                        "SACK_1"
                                        "SENK_1")
        (holetype1_om.Labels            "Through hole"
                                        "Blind hole"
                                        "Counter bore")
        (holetype1_om.TopOffset         0)
        (holetype1_om.BottomOffset      0)
        (holetype1_om.LeftOffset        2)
        (holetype1_om.RightOffset       10)
        (d1_txt.Label                   "Drill diameter")
        (d1_txt.Columns                 8)
        (d1_txt.AttachLeft              True)
        (d1_txt.AttachRight             True)
        (d1_txt.AttachTop               True)
        (d1_txt.AttachBottom            True)
        (d1_txt.Alignment               0)
        (d1_txt.TopOffset               0)
        (d1_txt.BottomOffset            0)
        (d1_txt.LeftOffset              0)
        (d1_txt.RightOffset             5)
        (d1_edit.Columns                5)
        (d1_edit.AttachTop              True)
        (d1_edit.AttachBottom           True)
        (d1_edit.TopOffset              0)
        (d1_edit.BottomOffset           0)
        (d1_edit.LeftOffset             0)
        (d1_edit.RightOffset            0)
        (bt1_txt.Label                  "Drill depth")
        (bt1_txt.Columns                8)
        (bt1_txt.Mapped                 True)
        (bt1_txt.AttachLeft             True)
        (bt1_txt.AttachRight            True)
        (bt1_txt.AttachTop              True)
        (bt1_txt.AttachBottom           True)
        (bt1_txt.Alignment              0)
        (bt1_txt.TopOffset              5)
        (bt1_txt.BottomOffset           0)
        (bt1_txt.LeftOffset             0)
        (bt1_txt.RightOffset            5)
        (bt1_spin.Columns               5)
        (bt1_spin.Mapped                True)
        (bt1_spin.AttachLeft            True)
        (bt1_spin.AttachRight           True)
        (bt1_spin.AttachTop             True)
        (bt1_spin.AttachBottom          True)
        (bt1_spin.MinColumns            4)
        (bt1_spin.TopOffset             5)
        (bt1_spin.BottomOffset          0)
        (bt1_spin.LeftOffset            0)
        (bt1_spin.RightOffset           0)
        (bt1_spin.InputType             3)
        (bt1_spin.Digits                2)
        (bdm1_txt.Label                 "Counter bore diameter")
        (bdm1_txt.Columns               8)
        (bdm1_txt.Mapped                True)
        (bdm1_txt.AttachLeft            True)
        (bdm1_txt.AttachRight           True)
        (bdm1_txt.AttachTop             True)
        (bdm1_txt.AttachBottom          True)
        (bdm1_txt.Alignment             0)
        (bdm1_txt.TopOffset             5)
        (bdm1_txt.BottomOffset          0)
        (bdm1_txt.LeftOffset            0)
        (bdm1_txt.RightOffset           5)
        (bdm1_spin.Columns              5)
        (bdm1_spin.Mapped               True)
        (bdm1_spin.AttachLeft           True)
        (bdm1_spin.AttachRight          True)
        (bdm1_spin.AttachTop            True)
        (bdm1_spin.AttachBottom         True)
        (bdm1_spin.MinColumns           4)
        (bdm1_spin.TopOffset            5)
        (bdm1_spin.BottomOffset         0)
        (bdm1_spin.LeftOffset           0)
        (bdm1_spin.RightOffset          0)
        (bdm1_spin.InputType            3)
        (bdm1_spin.Digits               2)
        (tol1_txt.Label                 "Tolerance")
        (tol1_txt.AttachLeft            True)
        (tol1_txt.AttachTop             True)
        (tol1_txt.Alignment             0)
        (tol1_txt.TopOffset             5)
        (tol1_txt.BottomOffset          5)
        (tol1_txt.LeftOffset            0)
        (tol1_txt.RightOffset           0)
        (tol1_txt.FontStyle             8)
        (tol1_combo.Columns             8)
        (tol1_combo.TopOffset           0)
        (tol1_combo.BottomOffset        0)
        (tol1_combo.LeftOffset          2)
        (tol1_combo.RightOffset         10)
        (tolupper1_txt.Label            "Upper tolerance")
        (tolupper1_txt.Columns          8)
        (tolupper1_txt.AttachLeft       True)
        (tolupper1_txt.AttachRight      True)
        (tolupper1_txt.AttachTop        True)
        (tolupper1_txt.AttachBottom     True)
        (tolupper1_txt.Alignment        0)
        (tolupper1_txt.TopOffset        0)
        (tolupper1_txt.BottomOffset     0)
        (tolupper1_txt.LeftOffset       0)
        (tolupper1_txt.RightOffset      5)
        (tolupper1_edit.Columns         5)
        (tolupper1_edit.TopOffset       0)
        (tolupper1_edit.BottomOffset    0)
        (tolupper1_edit.LeftOffset      0)
        (tolupper1_edit.RightOffset     0)
        (tollower1_txt.Label            "Lower tolerance")
        (tollower1_txt.Columns          8)
        (tollower1_txt.AttachLeft       True)
        (tollower1_txt.AttachRight      True)
        (tollower1_txt.AttachTop        True)
        (tollower1_txt.AttachBottom     True)
        (tollower1_txt.Alignment        0)
        (tollower1_txt.TopOffset        5)
        (tollower1_txt.BottomOffset     0)
        (tollower1_txt.LeftOffset       0)
        (tollower1_txt.RightOffset      5)
        (tollower1_edit.Columns         5)
        (tollower1_edit.TopOffset       5)
        (tollower1_edit.BottomOffset    0)
        (tollower1_edit.LeftOffset      0)
        (tollower1_edit.RightOffset     0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     5)
        (.BottomOffset                  0)
        (.LeftOffset                    5)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1 1 1 1 1 1) (Cols 1 1 1)
                holetype1_txt
                (Pos 2 1)
                holetype1_om
                d1_txt
                d1_edit
                t1_spin
                bt1_txt
                bt1_spin
                (Pos 4 2)
                bdm1_txt
                bdm1_spin
                tol1_txt
                (Pos 6 1)
                tol1_combo
                tolupper1_txt
                tolupper1_edit
                (Pos 7 2)
                tollower1_txt
                tollower1_edit
            )
        )
    )
)

(Layout holetype2_layout
    (Components
        (CheckButton                    holetype2_check)
        (SubLayout                      holetype2_data_layout)
    )

    (Resources
        (holetype2_check.Label          "Bottom Bore")
        (holetype2_check.AttachLeft     True)
        (holetype2_check.AttachRight    True)
        (holetype2_check.AttachTop      True)
        (holetype2_check.AttachBottom   True)
        (holetype2_check.TopOffset      0)
        (holetype2_check.BottomOffset   0)
        (holetype2_check.LeftOffset     0)
        (holetype2_check.RightOffset    0)
        (holetype2_check.FontStyle      8)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                holetype2_check
                holetype2_data_layout
            )
        )
    )
)

(Layout holetype2_data_layout
    (Components
        (Label                          holetype2_txt)
        (OptionMenu                     holetype2_om)
        (Label                          d2_txt)
        (InputPanel                     d2_edit)
        (Label                          bt2_txt)
        (SpinBox                        bt2_spin)
        (Label                          bdm2_txt)
        (SpinBox                        bdm2_spin)
        (Label                          tol2_txt)
        (OptionMenu                     tol2_combo)
        (Label                          tolupper2_txt)
        (InputPanel                     tolupper2_edit)
        (Label                          tollower2_txt)
        (InputPanel                     tollower2_edit)
    )

    (Resources
        (holetype2_txt.Label            "Hole Type")
        (holetype2_txt.AttachLeft       True)
        (holetype2_txt.AttachTop        True)
        (holetype2_txt.Alignment        0)
        (holetype2_txt.TopOffset        0)
        (holetype2_txt.BottomOffset     5)
        (holetype2_txt.LeftOffset       0)
        (holetype2_txt.RightOffset      0)
        (holetype2_txt.FontStyle        8)
        (holetype2_om.Columns           8)
        (holetype2_om.VisibleRows       3)
        (holetype2_om.Names             "DURCH_2"
                                        "SACK_2"
                                        "SENK_2")
        (holetype2_om.Labels            "Through hole"
                                        "Blind hole"
                                        "Counter bore")
        (holetype2_om.TopOffset         0)
        (holetype2_om.BottomOffset      0)
        (holetype2_om.LeftOffset        2)
        (holetype2_om.RightOffset       10)
        (d2_txt.Label                   "Drill diameter")
        (d2_txt.Columns                 8)
        (d2_txt.AttachLeft              True)
        (d2_txt.AttachRight             True)
        (d2_txt.AttachTop               True)
        (d2_txt.AttachBottom            True)
        (d2_txt.Alignment               0)
        (d2_txt.TopOffset               0)
        (d2_txt.BottomOffset            0)
        (d2_txt.LeftOffset              0)
        (d2_txt.RightOffset             5)
        (d2_edit.Columns                5)
        (d2_edit.AttachTop              True)
        (d2_edit.AttachBottom           True)
        (d2_edit.TopOffset              0)
        (d2_edit.BottomOffset           0)
        (d2_edit.LeftOffset             0)
        (d2_edit.RightOffset            0)
        (bt2_txt.Label                  "Drill depth")
        (bt2_txt.Columns                8)
        (bt2_txt.Mapped                 True)
        (bt2_txt.AttachLeft             True)
        (bt2_txt.AttachRight            True)
        (bt2_txt.AttachTop              True)
        (bt2_txt.AttachBottom           True)
        (bt2_txt.Alignment              0)
        (bt2_txt.TopOffset              5)
        (bt2_txt.BottomOffset           0)
        (bt2_txt.LeftOffset             0)
        (bt2_txt.RightOffset            5)
        (bt2_spin.Columns               5)
        (bt2_spin.Mapped                True)
        (bt2_spin.AttachLeft            True)
        (bt2_spin.AttachRight           True)
        (bt2_spin.AttachTop             True)
        (bt2_spin.AttachBottom          True)
        (bt2_spin.MinColumns            4)
        (bt2_spin.TopOffset             5)
        (bt2_spin.BottomOffset          0)
        (bt2_spin.LeftOffset            0)
        (bt2_spin.RightOffset           0)
        (bt2_spin.InputType             3)
        (bt2_spin.Digits                2)
        (bdm2_txt.Label                 "Counter bore diameter")
        (bdm2_txt.Columns               8)
        (bdm2_txt.Mapped                True)
        (bdm2_txt.AttachLeft            True)
        (bdm2_txt.AttachRight           True)
        (bdm2_txt.AttachTop             True)
        (bdm2_txt.AttachBottom          True)
        (bdm2_txt.Alignment             0)
        (bdm2_txt.TopOffset             5)
        (bdm2_txt.BottomOffset          0)
        (bdm2_txt.LeftOffset            0)
        (bdm2_txt.RightOffset           5)
        (bdm2_spin.Columns              5)
        (bdm2_spin.Mapped               True)
        (bdm2_spin.AttachLeft           True)
        (bdm2_spin.AttachRight          True)
        (bdm2_spin.AttachTop            True)
        (bdm2_spin.AttachBottom         True)
        (bdm2_spin.MinColumns           4)
        (bdm2_spin.TopOffset            5)
        (bdm2_spin.BottomOffset         0)
        (bdm2_spin.LeftOffset           0)
        (bdm2_spin.RightOffset          0)
        (bdm2_spin.InputType            3)
        (bdm2_spin.Digits               2)
        (tol2_txt.Label                 "Tolerance")
        (tol2_txt.AttachLeft            True)
        (tol2_txt.AttachTop             True)
        (tol2_txt.Alignment             0)
        (tol2_txt.TopOffset             5)
        (tol2_txt.BottomOffset          5)
        (tol2_txt.LeftOffset            0)
        (tol2_txt.RightOffset           0)
        (tol2_txt.FontStyle             8)
        (tol2_combo.Columns             8)
        (tol2_combo.TopOffset           0)
        (tol2_combo.BottomOffset        0)
        (tol2_combo.LeftOffset          2)
        (tol2_combo.RightOffset         10)
        (tolupper2_txt.Label            "Upper tolerance")
        (tolupper2_txt.Columns          8)
        (tolupper2_txt.AttachLeft       True)
        (tolupper2_txt.AttachRight      True)
        (tolupper2_txt.AttachTop        True)
        (tolupper2_txt.AttachBottom     True)
        (tolupper2_txt.Alignment        0)
        (tolupper2_txt.TopOffset        0)
        (tolupper2_txt.BottomOffset     0)
        (tolupper2_txt.LeftOffset       0)
        (tolupper2_txt.RightOffset      5)
        (tolupper2_edit.Columns         5)
        (tolupper2_edit.TopOffset       0)
        (tolupper2_edit.BottomOffset    0)
        (tolupper2_edit.LeftOffset      0)
        (tolupper2_edit.RightOffset     0)
        (tollower2_txt.Label            "Lower tolerance")
        (tollower2_txt.Columns          8)
        (tollower2_txt.AttachLeft       True)
        (tollower2_txt.AttachRight      True)
        (tollower2_txt.AttachTop        True)
        (tollower2_txt.AttachBottom     True)
        (tollower2_txt.Alignment        0)
        (tollower2_txt.TopOffset        5)
        (tollower2_txt.BottomOffset     0)
        (tollower2_txt.LeftOffset       0)
        (tollower2_txt.RightOffset      5)
        (tollower2_edit.Columns         5)
        (tollower2_edit.TopOffset       5)
        (tollower2_edit.BottomOffset    0)
        (tollower2_edit.LeftOffset      0)
        (tollower2_edit.RightOffset     0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     5)
        (.BottomOffset                  0)
        (.LeftOffset                    5)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1 1 1 1 1 1) (Cols 1 1 1)
                holetype2_txt
                (Pos 2 1)
                holetype2_om
                d2_txt
                d2_edit
                (Pos 3 2)
                bt2_txt
                bt2_spin
                (Pos 4 2)
                bdm2_txt
                bdm2_spin
                tol2_txt
                (Pos 6 1)
                tol2_combo
                tolupper2_txt
                tolupper2_edit
                (Pos 7 2)
                tollower2_txt
                tollower2_edit
            )
        )
    )
)

(Layout footer2_layout
    (Components
        (PushButton                     pb_Cancel2)
        (PushButton                     pb_OK2)
        (Separator                      Separator8)
    )

    (Resources
        (pb_Cancel2.Label               "Cancel")
        (pb_Cancel2.Columns             5)
        (pb_Cancel2.ButtonStyle         2)
        (pb_Cancel2.AttachRight         True)
        (pb_Cancel2.Alignment           1)
        (pb_Cancel2.TopOffset           10)
        (pb_Cancel2.BottomOffset        10)
        (pb_Cancel2.LeftOffset          0)
        (pb_Cancel2.RightOffset         10)
        (pb_OK2.Label                   "OK")
        (pb_OK2.Columns                 5)
        (pb_OK2.ButtonStyle             2)
        (pb_OK2.AttachRight             True)
        (pb_OK2.TopOffset               10)
        (pb_OK2.BottomOffset            10)
        (pb_OK2.LeftOffset              0)
        (pb_OK2.RightOffset             8)
        (Separator8.AttachBottom        True)
        (Separator8.TopOffset           0)
        (Separator8.BottomOffset        0)
        (Separator8.LeftOffset          0)
        (Separator8.RightOffset         0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                Separator8
                (Grid (Rows 1) (Cols 1 0)
                    pb_OK2
                    pb_Cancel2
                )
            )
        )
    )
)
