(Dialog ProTKDialogProfileMove
    (Components
        (SubLayout                      LayMain)
        (SubLayout                      footer_layout)
        (Separator                      S07)
    )

    (Resources
        (S07.AttachBottom               True)
        (S07.TopOffset                  0)
        (S07.BottomOffset               12)
        (S07.LeftOffset                 0)
        (S07.RightOffset                0)
        (.Label                         "Move Profile")
        (.StartLocation                 3)
        (.ModalOveride                  2)
        (.Resizeable                    False)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.DefaultButton                 "pb_apply")
        (.Layout
            (Grid (Rows 1 0 0) (Cols 1)
                LayMain
                S07
                footer_layout
            )
        )
    )
)

(Layout LayMain
    (Components
        (SubLayout                      LayComponent)
    )

    (Resources
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     16)
        (.BottomOffset                  10)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0) (Cols 1)
                LayComponent
            )
        )
    )
)

(Layout LayComponent
    (Components
        (SubLayout                      LaySelProfile)
        (SubLayout                      LayPosRot)
    )

    (Resources
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                LaySelProfile
                LayPosRot
            )
        )
    )
)

(Layout LaySelProfile
    (Components
        (Label                          lbHeaderSelProfile)
        (SubLayout                      LaySelProfileComponent)
        (Label                          lbHeaderSelRef)
        (SubLayout                      LaySelRefComponent)
        (Separator                      Separator1)
    )

    (Resources
        (lbHeaderSelProfile.Label       "Profiles to Move")
        (lbHeaderSelProfile.AttachLeft  True)
        (lbHeaderSelProfile.AttachTop   True)
        (lbHeaderSelProfile.TopOffset   0)
        (lbHeaderSelProfile.BottomOffset 5)
        (lbHeaderSelProfile.LeftOffset  0)
        (lbHeaderSelProfile.RightOffset 0)
        (lbHeaderSelProfile.FontStyle   8)
        (lbHeaderSelRef.Label           "Reference Geometry")
        (lbHeaderSelRef.Sensitive       False)
        (lbHeaderSelRef.AttachLeft      True)
        (lbHeaderSelRef.AttachTop       True)
        (lbHeaderSelRef.TopOffset       0)
        (lbHeaderSelRef.BottomOffset    5)
        (lbHeaderSelRef.LeftOffset      0)
        (lbHeaderSelRef.RightOffset     0)
        (lbHeaderSelRef.FontStyle       8)
        (Separator1.TopOffset           15)
        (Separator1.BottomOffset        12)
        (Separator1.LeftOffset          0)
        (Separator1.RightOffset         0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.Layout
            (Grid (Rows 0 1 0 0 0) (Cols 1)
                lbHeaderSelProfile
                LaySelProfileComponent
                lbHeaderSelRef
                LaySelRefComponent
                Separator1
            )
        )
    )
)

(Layout LaySelProfileComponent
    (Components
        (List                           lsProfileList)
    )

    (Resources
        (lsProfileList.SelectionPolicy  4)
        (lsProfileList.VisibleRows      6)
        (lsProfileList.ModalOveride     1)
        (lsProfileList.Resizeable       True)
        (lsProfileList.MinRows          5)
        (lsProfileList.PopupMenu        "mpSelProfile")
        (lsProfileList.BackgroundColor  31456491)
        (lsProfileList.TopOffset        0)
        (lsProfileList.BottomOffset     0)
        (lsProfileList.LeftOffset       0)
        (lsProfileList.RightOffset      0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1)
                lsProfileList
            )
        )
    )
)

(Layout LaySelRefComponent
    (Components
        (Table                          tblRef)
    )

    (Resources
        (tblRef.Sensitive               False)
        (tblRef.Columns                 10)
        (tblRef.VisibleRows             1)
        (tblRef.MinColumns              10)
        (tblRef.BackgroundColor         31456491)
        (tblRef.TopOffset               0)
        (tblRef.BottomOffset            0)
        (tblRef.LeftOffset              0)
        (tblRef.RightOffset             0)
        (tblRef.ScrollBarPosition       5)
        (tblRef.RowNames                "row_1")
        (tblRef.ColumnNames             "column_1")
        (tblRef.ScrollBarsWhenNeeded    False)
        (tblRef.ColumnWidths            25)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1)
                tblRef
            )
        )
    )
)


(Layout LayPosRot
    (Components
        (SubLayout                      LayMoveProfile)
        (SubLayout                      LayPosRotComponents)
    )

    (Resources
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                LayMoveProfile
                LayPosRotComponents
            )
        )
    )
)

(Layout LayMoveProfile
    (Components
        (Label                          lbHeaderMove)
        (SubLayout                      LayMoveProfileComponents)
    )

    (Resources
        (lbHeaderMove.Label             "Move")
        (lbHeaderMove.AttachLeft        True)
        (lbHeaderMove.TopOffset         0)
        (lbHeaderMove.BottomOffset      5)
        (lbHeaderMove.LeftOffset        0)
        (lbHeaderMove.RightOffset       0)
        (lbHeaderMove.FontStyle         8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                lbHeaderMove
                LayMoveProfileComponents
            )
        )
    )
)

(Layout LayMoveProfileComponents
    (Components
        (CheckButton                    cbToSelectedCurve)
        (CheckButton                    cbToSelectedReference)
        (CheckButton                    cbResetMovement)
    )

    (Resources
        (cbToSelectedCurve.Bitmap       "afx_dia_move_mouse_pick_20x20.png")
        (cbToSelectedCurve.HelpText     "Align profile with the selected entity and reference curve.")
        (cbToSelectedCurve.ButtonStyle  2)
        (cbToSelectedCurve.ModalOveride 2)
        (cbToSelectedCurve.AttachLeft   True)
        (cbToSelectedCurve.KeyboardInput True)
        (cbToSelectedCurve.TopOffset    0)
        (cbToSelectedCurve.BottomOffset 0)
        (cbToSelectedCurve.LeftOffset   0)
        (cbToSelectedCurve.RightOffset  3)
        (cbToSelectedCurve.ButtonAlignment 441)
        (cbToSelectedReference.Bitmap   "afx_dia_move_align_20x20.png")
        (cbToSelectedReference.HelpText "Align profile with selected entities from profile and another part.")
        (cbToSelectedReference.ButtonStyle 2)
        (cbToSelectedReference.ModalOveride 2)
        (cbToSelectedReference.AttachLeft True)
        (cbToSelectedReference.KeyboardInput True)
        (cbToSelectedReference.TopOffset 0)
        (cbToSelectedReference.BottomOffset 0)
        (cbToSelectedReference.LeftOffset 0)
        (cbToSelectedReference.RightOffset 3)
        (cbToSelectedReference.ButtonAlignment 441)
        (cbResetMovement.Bitmap         "afx_dia_reset_20x20.png")
        (cbResetMovement.HelpText       "Reset profile move.")
        (cbResetMovement.ButtonStyle    2)
        (cbResetMovement.ModalOveride   2)
        (cbResetMovement.AttachRight    True)
        (cbResetMovement.KeyboardInput  True)
        (cbResetMovement.TopOffset      0)
        (cbResetMovement.BottomOffset   0)
        (cbResetMovement.LeftOffset     0)
        (cbResetMovement.RightOffset    3)
        (cbResetMovement.ButtonAlignment 441)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     5)
        (.BottomOffset                  5)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0) (Cols 0 0 1)
                cbToSelectedCurve
                cbToSelectedReference
                cbResetMovement
            )
        )
    )
)

(Layout LayPosRotComponents
    (Components
        (Separator                      S02)
        (SubLayout                      LayMoveToPos)
        (SubLayout                      LayValueToPos)
        (Label                          lbHeaderRotate)
        (SubLayout                      LayRotToPos)
        (SubLayout                      LayValueToRot)
    )

    (Resources
        (S02.AttachTop                  True)
        (S02.TopOffset                  10)
        (S02.BottomOffset               10)
        (S02.LeftOffset                 0)
        (S02.RightOffset                0)
        (lbHeaderRotate.Label           "Rotate")
        (lbHeaderRotate.AttachLeft      True)
        (lbHeaderRotate.AttachTop       True)
        (lbHeaderRotate.TopOffset       0)
        (lbHeaderRotate.BottomOffset    5)
        (lbHeaderRotate.LeftOffset      0)
        (lbHeaderRotate.RightOffset     0)
        (lbHeaderRotate.FontStyle       8)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     5)
        (.BottomOffset                  5)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1 1) (Cols 1)
                (Grid (Rows 0) (Cols 1 1 1)
                    LayMoveToPos
                    (Pos 1 3)
                    LayValueToPos
                )
                S02
                (Grid (Rows 1 0) (Cols 1 1 1)
                    lbHeaderRotate
                    (Pos 2 1)
                    LayRotToPos
                    (Pos 2 3)
                    LayValueToRot
                )
            )
        )
    )
)

(Layout LayMoveToPos
    (Components
        (CheckButton                    cbMoveTopLeft)
        (CheckButton                    cbMoveTopCenter)
        (CheckButton                    cbMoveTopRight)
        (CheckButton                    cbMoveCenterLeft)
        (CheckButton                    cbMoveCenter)
        (CheckButton                    cbMoveCenterRight)
        (CheckButton                    cbMoveBottomLeft)
        (CheckButton                    cbMoveBottomCenter)
        (CheckButton                    cbMoveBottomRight)
    )

    (Resources
        (cbMoveTopLeft.Bitmap           "afx_dia_profiles_pos_top_left_20x20.png")
        (cbMoveTopLeft.HelpText         "Move profile to top-left corner.")
        (cbMoveTopLeft.ButtonStyle      2)
        (cbMoveTopLeft.ModalOveride     2)
        (cbMoveTopLeft.AttachLeft       True)
        (cbMoveTopLeft.AttachTop        True)
        (cbMoveTopLeft.KeyboardInput    True)
        (cbMoveTopLeft.TopOffset        0)
        (cbMoveTopLeft.BottomOffset     3)
        (cbMoveTopLeft.LeftOffset       0)
        (cbMoveTopLeft.RightOffset      3)
        (cbMoveTopCenter.Bitmap         "afx_dia_profiles_pos_top_center_20x20.png")
        (cbMoveTopCenter.HelpText       "Move profile to top-center.")
        (cbMoveTopCenter.ButtonStyle    2)
        (cbMoveTopCenter.ModalOveride   2)
        (cbMoveTopCenter.AttachLeft     True)
        (cbMoveTopCenter.AttachTop      True)
        (cbMoveTopCenter.KeyboardInput  True)
        (cbMoveTopCenter.TopOffset      0)
        (cbMoveTopCenter.BottomOffset   3)
        (cbMoveTopCenter.LeftOffset     0)
        (cbMoveTopCenter.RightOffset    3)
        (cbMoveTopRight.Bitmap          "afx_dia_profiles_pos_top_right_20x20.png")
        (cbMoveTopRight.HelpText        "Move profile to top-right corner.")
        (cbMoveTopRight.ButtonStyle     2)
        (cbMoveTopRight.ModalOveride    2)
        (cbMoveTopRight.AttachLeft      True)
        (cbMoveTopRight.AttachTop       True)
        (cbMoveTopRight.KeyboardInput   True)
        (cbMoveTopRight.TopOffset       0)
        (cbMoveTopRight.BottomOffset    3)
        (cbMoveTopRight.LeftOffset      0)
        (cbMoveTopRight.RightOffset     3)
        (cbMoveCenterLeft.Bitmap        "afx_dia_profiles_pos_center_left_20x20.png")
        (cbMoveCenterLeft.HelpText      "Move profile to center-left.")
        (cbMoveCenterLeft.ButtonStyle   2)
        (cbMoveCenterLeft.ModalOveride  2)
        (cbMoveCenterLeft.AttachLeft    True)
        (cbMoveCenterLeft.AttachTop     True)
        (cbMoveCenterLeft.KeyboardInput True)
        (cbMoveCenterLeft.TopOffset     0)
        (cbMoveCenterLeft.BottomOffset  3)
        (cbMoveCenterLeft.LeftOffset    0)
        (cbMoveCenterLeft.RightOffset   3)
        (cbMoveCenter.Bitmap            "afx_dia_profiles_pos_center_center_20x20.png")
        (cbMoveCenter.HelpText          "Move profile to center.")
        (cbMoveCenter.ButtonStyle       2)
        (cbMoveCenter.ModalOveride      2)
        (cbMoveCenter.AttachLeft        True)
        (cbMoveCenter.AttachTop         True)
        (cbMoveCenter.KeyboardInput     True)
        (cbMoveCenter.TopOffset         0)
        (cbMoveCenter.BottomOffset      3)
        (cbMoveCenter.LeftOffset        0)
        (cbMoveCenter.RightOffset       3)
        (cbMoveCenterRight.Bitmap       "afx_dia_profiles_pos_center_right_20x20.png")
        (cbMoveCenterRight.HelpText     "Move profile to center-right.")
        (cbMoveCenterRight.ButtonStyle  2)
        (cbMoveCenterRight.ModalOveride 2)
        (cbMoveCenterRight.AttachLeft   True)
        (cbMoveCenterRight.AttachTop    True)
        (cbMoveCenterRight.KeyboardInput True)
        (cbMoveCenterRight.TopOffset    0)
        (cbMoveCenterRight.BottomOffset 3)
        (cbMoveCenterRight.LeftOffset   0)
        (cbMoveCenterRight.RightOffset  3)
        (cbMoveBottomLeft.Bitmap        "afx_dia_profiles_pos_bottom_left_20x20.png")
        (cbMoveBottomLeft.HelpText      "Move profile to bottom-left corner.")
        (cbMoveBottomLeft.ButtonStyle   2)
        (cbMoveBottomLeft.ModalOveride  2)
        (cbMoveBottomLeft.AttachLeft    True)
        (cbMoveBottomLeft.AttachTop     True)
        (cbMoveBottomLeft.KeyboardInput True)
        (cbMoveBottomLeft.TopOffset     0)
        (cbMoveBottomLeft.BottomOffset  0)
        (cbMoveBottomLeft.LeftOffset    0)
        (cbMoveBottomLeft.RightOffset   0)
        (cbMoveBottomCenter.Bitmap      "afx_dia_profiles_pos_bottom_center_20x20.png")
        (cbMoveBottomCenter.HelpText    "Move profile to bottom-center.")
        (cbMoveBottomCenter.ButtonStyle 2)
        (cbMoveBottomCenter.ModalOveride 2)
        (cbMoveBottomCenter.AttachLeft  True)
        (cbMoveBottomCenter.AttachTop   True)
        (cbMoveBottomCenter.KeyboardInput True)
        (cbMoveBottomCenter.TopOffset   0)
        (cbMoveBottomCenter.BottomOffset 0)
        (cbMoveBottomCenter.LeftOffset  0)
        (cbMoveBottomCenter.RightOffset 0)
        (cbMoveBottomRight.Bitmap       "afx_dia_profiles_pos_bottom_right_20x20.png")
        (cbMoveBottomRight.HelpText     "Move profile to bottom-right corner.")
        (cbMoveBottomRight.ButtonStyle  2)
        (cbMoveBottomRight.ModalOveride 2)
        (cbMoveBottomRight.AttachLeft   True)
        (cbMoveBottomRight.AttachTop    True)
        (cbMoveBottomRight.KeyboardInput True)
        (cbMoveBottomRight.TopOffset    0)
        (cbMoveBottomRight.BottomOffset 0)
        (cbMoveBottomRight.LeftOffset   0)
        (cbMoveBottomRight.RightOffset  0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   15)
        (.Layout
            (Grid (Rows 0 0 0) (Cols 0 0 1)
                cbMoveTopLeft
                cbMoveTopCenter
                cbMoveTopRight
                cbMoveCenterLeft
                cbMoveCenter
                cbMoveCenterRight
                cbMoveBottomLeft
                cbMoveBottomCenter
                cbMoveBottomRight
            )
        )
    )
)

(Layout LayValueToPos
    (Components
        (CheckButton                    cbValueToPos)
        (Label                          lbImageDim1)
        (Label                          lbImageDim2)
        (InputPanel                     ipPosDim1)
        (InputPanel                     ipPosDim2)
    )

    (Resources
        (cbValueToPos.Bitmap            "afx_dia_move_dimension_20x20.png")
        (cbValueToPos.HelpText          "Move profile by specific dimensions.")
        (cbValueToPos.ButtonStyle       2)
        (cbValueToPos.ModalOveride      1)
        (cbValueToPos.AttachLeft        True)
        (cbValueToPos.AttachTop         True)
        (cbValueToPos.KeyboardInput     True)
        (cbValueToPos.TopOffset         0)
        (cbValueToPos.BottomOffset      5)
        (cbValueToPos.LeftOffset        0)
        (cbValueToPos.RightOffset       0)
        (lbImageDim1.Bitmap             "afx_dia_dimension_1_29x13.png")
        (lbImageDim1.Sensitive          False)
        (lbImageDim1.AttachLeft         True)
        (lbImageDim1.TopOffset          0)
        (lbImageDim1.BottomOffset       0)
        (lbImageDim1.LeftOffset         0)
        (lbImageDim1.RightOffset        5)
        (lbImageDim2.Bitmap             "afx_dia_dimension_2_29x13.png")
        (lbImageDim2.Sensitive          False)
        (lbImageDim2.AttachLeft         True)
        (lbImageDim2.TopOffset          0)
        (lbImageDim2.BottomOffset       5)
        (lbImageDim2.LeftOffset         0)
        (lbImageDim2.RightOffset        5)
        (ipPosDim1.Sensitive            False)
        (ipPosDim1.Columns              3)
        (ipPosDim1.ModalOveride         1)
        (ipPosDim1.AttachRight          False)
        (ipPosDim1.AttachTop            True)
        (ipPosDim1.TopOffset            0)
        (ipPosDim1.BottomOffset         5)
        (ipPosDim1.LeftOffset           0)
        (ipPosDim1.RightOffset          0)
        (ipPosDim1.AutoHighlight        True)
        (ipPosDim2.Sensitive            False)
        (ipPosDim2.Columns              3)
        (ipPosDim2.ModalOveride         1)
        (ipPosDim2.AttachRight          False)
        (ipPosDim2.AttachTop            True)
        (ipPosDim2.TopOffset            0)
        (ipPosDim2.BottomOffset         0)
        (ipPosDim2.LeftOffset           0)
        (ipPosDim2.RightOffset          0)
        (ipPosDim2.AutoHighlight        True)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                cbValueToPos
                (Grid (Rows 0 1) (Cols 1 1)
                    lbImageDim1
                    ipPosDim1
                    lbImageDim2
                    ipPosDim2
                )
            )
        )
    )
)

(Layout LayRotToPos
    (Components
        (CheckButton                    cbRotminus90)
        (CheckButton                    cbRot0)
        (CheckButton                    cbRot180)
        (CheckButton                    cbRot90)
        (CheckButton                    cbSwitchStartEnd)
    )

    (Resources
        (cbRotminus90.Bitmap            "afx_dia_rot_minus_90_20x20.png")
        (cbRotminus90.HelpText          "Rotate profile by -90 degrees.")
        (cbRotminus90.ButtonStyle       2)
        (cbRotminus90.ModalOveride      2)
        (cbRotminus90.AttachLeft        True)
        (cbRotminus90.AttachTop         True)
        (cbRotminus90.KeyboardInput     True)
        (cbRotminus90.TopOffset         0)
        (cbRotminus90.BottomOffset      3)
        (cbRotminus90.LeftOffset        0)
        (cbRotminus90.RightOffset       3)
        (cbRot0.Bitmap                  "afx_dia_rot_0_20x20.png")
        (cbRot0.HelpText                "Reset profile rotation.")
        (cbRot0.ButtonStyle             2)
        (cbRot0.ModalOveride            2)
        (cbRot0.AttachLeft              True)
        (cbRot0.AttachTop               True)
        (cbRot0.KeyboardInput           True)
        (cbRot0.TopOffset               0)
        (cbRot0.BottomOffset            3)
        (cbRot0.LeftOffset              0)
        (cbRot0.RightOffset             3)
        (cbRot180.Bitmap                "afx_dia_rot_180_20x20.png")
        (cbRot180.HelpText              "Rotate profile by 180 degrees.")
        (cbRot180.ButtonStyle           2)
        (cbRot180.ModalOveride          2)
        (cbRot180.AttachLeft            True)
        (cbRot180.AttachTop             True)
        (cbRot180.KeyboardInput         True)
        (cbRot180.TopOffset             0)
        (cbRot180.BottomOffset          3)
        (cbRot180.LeftOffset            0)
        (cbRot180.RightOffset           3)
        (cbRot90.Bitmap                 "afx_dia_rot_plus_90_20x20.png")
        (cbRot90.HelpText               "Rotate profile by +90 degrees.")
        (cbRot90.ButtonStyle            2)
        (cbRot90.ModalOveride           2)
        (cbRot90.AttachLeft             True)
        (cbRot90.AttachTop              True)
        (cbRot90.KeyboardInput          True)
        (cbRot90.TopOffset              0)
        (cbRot90.BottomOffset           3)
        (cbRot90.LeftOffset             0)
        (cbRot90.RightOffset            3)
        (cbSwitchStartEnd.Bitmap        "afx_dia_rot_switch_start_end_20x20.png")
        (cbSwitchStartEnd.HelpText      "Toggle profile start and end points on reference curve.")
        (cbSwitchStartEnd.ButtonStyle   2)
        (cbSwitchStartEnd.ModalOveride  2)
        (cbSwitchStartEnd.AttachLeft    True)
        (cbSwitchStartEnd.AttachTop     True)
        (cbSwitchStartEnd.KeyboardInput True)
        (cbSwitchStartEnd.TopOffset     0)
        (cbSwitchStartEnd.BottomOffset  3)
        (cbSwitchStartEnd.LeftOffset    0)
        (cbSwitchStartEnd.RightOffset   3)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   15)
        (.Layout
            (Grid (Rows 0 0 1) (Cols 1 0)
                cbRotminus90
                cbRot0
                cbRot180
                cbRot90
                cbSwitchStartEnd
            )
        )
    )
)

(Layout LayValueToRot
    (Components
        (CheckButton                    cbValueToRot)
        (Label                          lbImageDim1_1)
        (InputPanel                     ipRotDim1)
    )

    (Resources
        (cbValueToRot.Bitmap            "afx_dia_rot_value_20x20.png")
        (cbValueToRot.HelpText          "Rotate profile by specific value.")
        (cbValueToRot.ButtonStyle       2)
        (cbValueToRot.ModalOveride      1)
        (cbValueToRot.AttachLeft        True)
        (cbValueToRot.KeyboardInput     True)
        (cbValueToRot.TopOffset         0)
        (cbValueToRot.BottomOffset      5)
        (cbValueToRot.LeftOffset        0)
        (cbValueToRot.RightOffset       0)
        (lbImageDim1_1.Bitmap           "afx_dia_dimension_1_29x13.png")
        (lbImageDim1_1.Sensitive        False)
        (lbImageDim1_1.TopOffset        0)
        (lbImageDim1_1.BottomOffset     0)
        (lbImageDim1_1.LeftOffset       0)
        (lbImageDim1_1.RightOffset      5)
        (ipRotDim1.Sensitive            False)
        (ipRotDim1.Columns              3)
        (ipRotDim1.ModalOveride         1)
        (ipRotDim1.MinColumns           1)
        (ipRotDim1.TopOffset            0)
        (ipRotDim1.BottomOffset         5)
        (ipRotDim1.LeftOffset           0)
        (ipRotDim1.RightOffset          0)
        (ipRotDim1.AutoHighlight        True)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                cbValueToRot
                (Grid (Rows 1) (Cols 0 1)
                    lbImageDim1_1
                    ipRotDim1
                )
            )
        )
    )
)

(Layout footer_layout
    (Components
        (PushButton                     pb_apply)
        (PushButton                     pb_ok)
        (PushButton                     pb_close)
    )

    (Resources
        (pb_apply.Label                 "Repeat")
        (pb_apply.Columns               5)
        (pb_apply.ButtonStyle           2)
        (pb_apply.ModalOveride          2)
        (pb_apply.AttachLeft            True)
        (pb_apply.KeyboardInput         True)
        (pb_apply.TopOffset             0)
        (pb_apply.BottomOffset          0)
        (pb_apply.LeftOffset            0)
        (pb_apply.RightOffset           15)
        (pb_ok.Label                    "OK")
        (pb_ok.Columns                  5)
        (pb_ok.ButtonStyle              2)
        (pb_ok.ModalOveride             2)
        (pb_ok.AttachRight              True)
        (pb_ok.KeyboardInput            True)
        (pb_ok.TopOffset                0)
        (pb_ok.BottomOffset             0)
        (pb_ok.LeftOffset               0)
        (pb_ok.RightOffset              8)
        (pb_close.Label                 "Cancel")
        (pb_close.Columns               5)
        (pb_close.ButtonStyle           2)
        (pb_close.ModalOveride          2)
        (pb_close.AttachRight           True)
        (pb_close.KeyboardInput         True)
        (pb_close.TopOffset             0)
        (pb_close.BottomOffset          0)
        (pb_close.LeftOffset            0)
        (pb_close.RightOffset           8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.Alignment                     1)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    10)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0) (Cols 0 1 0)
                pb_apply
                pb_ok
                pb_close
            )
        )
    )
)

(MenuPane mpSelProfile
    (Components
        (PushButton                     pbRmbRemove)
        (PushButton                     pbRmbRemoveAll)
    )

    (Resources
        (pbRmbRemove.Label              "Remove")
        (pbRmbRemove.ModalOveride       2)
        (pbRmbRemove.KeyboardInput      True)
        (pbRmbRemoveAll.Label           "Remove All")
        (pbRmbRemoveAll.ModalOveride    2)
        (pbRmbRemoveAll.KeyboardInput   True)
    )
)
