(Dialog ProTKDialogJointsBasic
    (Components
        (SubLayout                      LayoutContentArea)
        (Separator                      S00)
        (SubLayout                      LayoutCommitBar)
    )

    (Resources
        (S00.TopOffset                  16)
        (S00.BottomOffset               10)
        (.Label                         "Basic Joints")
        (.StartLocation                 3)
        (.ModalOveride                  2)
        (.Resizeable                    False)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.DefaultButton                 "pb_apply")
        (.Layout
            (Grid (Rows 0 1 0) (Cols 0)
                LayoutContentArea
                S00
                LayoutCommitBar
            )
        )
    )
)

(Layout LayoutContentArea
    (Components
        (SubLayout                      LayoutActions)
        (Separator                      S01)
        (SubLayout                      LayoutJointType)
        (Separator                      S02)
        (SubLayout                      LayoutOffset)
        (Separator                      S03)
        (SubLayout                      LayoutReferences)
    )

    (Resources
        (S01.TopOffset                  10)
        (S01.BottomOffset               10)
        (S01.LeftOffset                 0)
        (S01.RightOffset                0)
        (S02.TopOffset                  10)
        (S02.BottomOffset               10)
        (S02.LeftOffset                 0)
        (S02.RightOffset                0)
        (S03.TopOffset                  10)
        (S03.BottomOffset               10)
        (S03.LeftOffset                 0)
        (S03.RightOffset                0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 0 0 1 0 1 0) (Cols 1)
                LayoutActions
                S01
                LayoutJointType
                S02
                LayoutOffset
                S03
                LayoutReferences
            )
        )
    )
)

(Layout LayoutActions
    (Components
        (CheckButton                    cbNew)
        (CheckButton                    cbCopy)
        (CheckButton                    cbEdit)
        (CheckButton                    cbDelete)
        (CheckButton                    cbVisible)
        (SubLayout                      LayoutJointSelectionLabels)
        (Table                          tblRefJoint)
        (CheckButton                    cbResetEnds)
        (Label                          lbActions)
    )

    (Resources
        (cbNew.Bitmap                   "afx_dia_joint_new_20x20.png")
        (cbNew.HelpText                 "Define new joint.")
        (cbNew.ButtonStyle              2)
        (cbNew.ModalOveride             2)
        (cbNew.AttachLeft               True)
        (cbNew.HelpTag                  "AFX_JointsBasicNew")
        (cbNew.KeyboardInput            True)
        (cbNew.TopOffset                0)
        (cbNew.BottomOffset             0)
        (cbNew.LeftOffset               0)
        (cbNew.RightOffset              3)
        (cbCopy.Bitmap                  "afx_dia_joint_copy_20x20.png")
        (cbCopy.HelpText                "Copy joint.")
        (cbCopy.ButtonStyle             2)
        (cbCopy.ModalOveride            2)
        (cbCopy.AttachLeft              True)
        (cbCopy.HelpTag                 "AFX_JointsBasicCopy")
        (cbCopy.KeyboardInput           True)
        (cbCopy.TopOffset               0)
        (cbCopy.BottomOffset            0)
        (cbCopy.LeftOffset              0)
        (cbCopy.RightOffset             3)
        (cbEdit.Bitmap                  "afx_dia_joint_modify_20x20.png")
        (cbEdit.HelpText                "Modify joint.")
        (cbEdit.ButtonStyle             2)
        (cbEdit.ModalOveride            2)
        (cbEdit.HelpTag                 "AFX_JointsBasicEdit")
        (cbEdit.KeyboardInput           True)
        (cbEdit.TopOffset               0)
        (cbEdit.BottomOffset            0)
        (cbEdit.LeftOffset              0)
        (cbEdit.RightOffset             3)
        (cbDelete.Bitmap                "afx_dia_delete_20x20.png")
        (cbDelete.HelpText              "Delete joint.")
        (cbDelete.ButtonStyle           2)
        (cbDelete.ModalOveride          2)
        (cbDelete.AttachLeft            True)
        (cbDelete.HelpTag               "AFX_JointsBasicDelete")
        (cbDelete.KeyboardInput         True)
        (cbDelete.TopOffset             0)
        (cbDelete.BottomOffset          0)
        (cbDelete.LeftOffset            0)
        (cbDelete.RightOffset           3)
        (cbVisible.Bitmap               "afx_dia_joints_show_symbols_20x20.png")
        (cbVisible.HelpText             "Show or hide joint symbols.")
        (cbVisible.Set                  True)
        (cbVisible.ButtonStyle          2)
        (cbVisible.ModalOveride         2)
        (cbVisible.AttachLeft           True)
        (cbVisible.KeyboardInput        True)
        (cbVisible.TopOffset            0)
        (cbVisible.BottomOffset         0)
        (cbVisible.LeftOffset           0)
        (cbVisible.RightOffset          0)
        (tblRefJoint.Columns            10)
        (tblRefJoint.VisibleRows        1)
        (tblRefJoint.ModalOveride       2)
        (tblRefJoint.MinColumns         10)
        (tblRefJoint.BackgroundColor    31456491)
        (tblRefJoint.TopOffset          0)
        (tblRefJoint.BottomOffset       5)
        (tblRefJoint.LeftOffset         0)
        (tblRefJoint.RightOffset        0)
        (tblRefJoint.ScrollBarPosition  5)
        (tblRefJoint.RowNames           "row_1")
        (tblRefJoint.ColumnNames        "column_1")
        (tblRefJoint.ScrollBarsWhenNeeded False)
        (tblRefJoint.ColumnWidths       25)
        (cbResetEnds.Label              "Reset profile ends")
        (cbResetEnds.Set                True)
        (cbResetEnds.ModalOveride       2)
        (cbResetEnds.AttachLeft         True)
        (cbResetEnds.KeyboardInput      True)
        (cbResetEnds.TopOffset          3)
        (cbResetEnds.BottomOffset       0)
        (cbResetEnds.LeftOffset         0)
        (cbResetEnds.RightOffset        0)
        (lbActions.Label                "Joint Actions")
        (lbActions.AttachLeft           True)
        (lbActions.AttachTop            True)
        (lbActions.TopOffset            0)
        (lbActions.BottomOffset         5)
        (lbActions.LeftOffset           0)
        (lbActions.RightOffset          0)
        (lbActions.FontStyle            8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1 1 1) (Cols 1)
                (Grid (Rows 0 0) (Cols 1 0)
                    lbActions
                    (Pos 2 1)
                    (Grid (Rows 0) (Cols 0 0 0 1)
                        cbNew
                        cbCopy
                        cbEdit
                        cbDelete
                    )
                    cbVisible
                )
                LayoutJointSelectionLabels
                tblRefJoint
                cbResetEnds
            )
        )
    )
)


(Layout LayoutJointSelectionLabels
    (Components
        (Label                          lbRefJoint)
        (Label                          lbRefJoint_1)
        (Label                          lbRefJoint_2)
        (Label                          lbRefJoint_3)
    )

    (Resources
        (lbRefJoint.Label               "-")
        (lbRefJoint.AttachLeft          True)
        (lbRefJoint.AttachTop           True)
        (lbRefJoint.TopOffset           0)
        (lbRefJoint.BottomOffset        0)
        (lbRefJoint.LeftOffset          0)
        (lbRefJoint.RightOffset         0)
        (lbRefJoint.FontStyle           8)
        (lbRefJoint_1.Label             "Joint to Copy")
        (lbRefJoint_1.Visible           False)
        (lbRefJoint_1.AttachLeft        True)
        (lbRefJoint_1.AttachTop         True)
        (lbRefJoint_1.TopOffset         0)
        (lbRefJoint_1.BottomOffset      0)
        (lbRefJoint_1.LeftOffset        0)
        (lbRefJoint_1.RightOffset       0)
        (lbRefJoint_1.FontStyle         8)
        (lbRefJoint_2.Label             "Joint to Modify")
        (lbRefJoint_2.Visible           False)
        (lbRefJoint_2.AttachLeft        True)
        (lbRefJoint_2.AttachTop         True)
        (lbRefJoint_2.TopOffset         0)
        (lbRefJoint_2.BottomOffset      0)
        (lbRefJoint_2.LeftOffset        0)
        (lbRefJoint_2.RightOffset       0)
        (lbRefJoint_2.FontStyle         8)
        (lbRefJoint_3.Label             "Joint to Delete")
        (lbRefJoint_3.Visible           False)
        (lbRefJoint_3.AttachLeft        True)
        (lbRefJoint_3.AttachTop         True)
        (lbRefJoint_3.TopOffset         0)
        (lbRefJoint_3.BottomOffset      0)
        (lbRefJoint_3.LeftOffset        0)
        (lbRefJoint_3.RightOffset       0)
        (lbRefJoint_3.FontStyle         8)
        (.AttachLeft                    True)
        (.TopOffset                     10)
        (.BottomOffset                  5)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 1 1)
                lbRefJoint
                lbRefJoint_1
                lbRefJoint_2
                lbRefJoint_3
            )
        )
    )
)

(Layout LayoutJointType
    (Components
        (SubLayout                      LayoutJoinBothEnds)
        (Separator                      S01_1)
        (SubLayout                      LayoutJoinOneEnd)
        (Separator                      S01_2)
        (SubLayout                      LayoutJoinEndToSurf)
        (Separator                      S01_3)
        (SubLayout                      LayoutJoinDatums)
    )

    (Resources
        (S01_1.TopOffset                10)
        (S01_1.BottomOffset             10)
        (S01_1.LeftOffset               0)
        (S01_1.RightOffset              0)
        (S01_2.TopOffset                10)
        (S01_2.BottomOffset             10)
        (S01_2.LeftOffset               0)
        (S01_2.RightOffset              0)
        (S01_3.TopOffset                10)
        (S01_3.BottomOffset             10)
        (S01_3.LeftOffset               0)
        (S01_3.RightOffset              0)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1 1 1 1 1 1) (Cols 1)
                LayoutJoinBothEnds
                S01_1
                LayoutJoinOneEnd
                S01_2
                LayoutJoinEndToSurf
                S01_3
                LayoutJoinDatums
            )
        )
    )
)

(Layout LayoutJoinBothEnds
    (Components
        (Label                          lbJoinBothEnds)
        (SubLayout                      LayoutJoinBothEndsContent)
    )

    (Resources
        (lbJoinBothEnds.Label           "Join both Profile Ends")
        (lbJoinBothEnds.AttachLeft      True)
        (lbJoinBothEnds.AttachTop       True)
        (lbJoinBothEnds.TopOffset       0)
        (lbJoinBothEnds.BottomOffset    5)
        (lbJoinBothEnds.LeftOffset      0)
        (lbJoinBothEnds.RightOffset     0)
        (lbJoinBothEnds.FontStyle       8)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                lbJoinBothEnds
                LayoutJoinBothEndsContent
            )
        )
    )
)

(Layout LayoutJoinBothEndsContent
    (Components
        (CheckButton                    cbCornerJoint)
        (CheckButton                    cbCornerGap)
        (CheckButton                    cbCornerOverlap)
        (CheckButton                    cbMitreJoint)
    )

    (Resources
        (cbCornerJoint.Bitmap           "afx_dia_joints_corner_48x48.png")
        (cbCornerJoint.HelpText         "Define corner joint.")
        (cbCornerJoint.ButtonStyle      2)
        (cbCornerJoint.ModalOveride     2)
        (cbCornerJoint.AttachLeft       True)
        (cbCornerJoint.AttachTop        True)
        (cbCornerJoint.KeyboardInput    True)
        (cbCornerJoint.TopOffset        0)
        (cbCornerJoint.BottomOffset     3)
        (cbCornerJoint.LeftOffset       0)
        (cbCornerJoint.RightOffset      3)
        (cbCornerGap.Bitmap             "afx_dia_joints_corner_gap_48x48.png")
        (cbCornerGap.HelpText           "Define corner joint with gap.")
        (cbCornerGap.ButtonStyle        2)
        (cbCornerGap.ModalOveride       2)
        (cbCornerGap.AttachLeft         True)
        (cbCornerGap.AttachTop          True)
        (cbCornerGap.KeyboardInput      True)
        (cbCornerGap.TopOffset          0)
        (cbCornerGap.BottomOffset       3)
        (cbCornerGap.LeftOffset         0)
        (cbCornerGap.RightOffset        3)
        (cbCornerOverlap.Bitmap         "afx_dia_joints_corner_overlapp_48x48.png")
        (cbCornerOverlap.HelpText       "Define corner joint with overlap.")
        (cbCornerOverlap.ButtonStyle    2)
        (cbCornerOverlap.ModalOveride   2)
        (cbCornerOverlap.AttachLeft     True)
        (cbCornerOverlap.AttachTop      True)
        (cbCornerOverlap.KeyboardInput  True)
        (cbCornerOverlap.TopOffset      0)
        (cbCornerOverlap.BottomOffset   3)
        (cbCornerOverlap.LeftOffset     0)
        (cbCornerOverlap.RightOffset    3)
        (cbMitreJoint.Bitmap            "afx_dia_joints_mitre_48x48.png")
        (cbMitreJoint.HelpText          "Define miter joint.")
        (cbMitreJoint.ButtonStyle       2)
        (cbMitreJoint.ModalOveride      2)
        (cbMitreJoint.AttachLeft        True)
        (cbMitreJoint.AttachTop         True)
        (cbMitreJoint.KeyboardInput     True)
        (cbMitreJoint.TopOffset         0)
        (cbMitreJoint.BottomOffset      3)
        (cbMitreJoint.LeftOffset        0)
        (cbMitreJoint.RightOffset       3)
        (.AttachLeft                    True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 0 1 1 1)
                cbCornerJoint
                cbCornerGap
                cbCornerOverlap
                cbMitreJoint
            )
        )
    )
)

(Layout LayoutJoinOneEnd
    (Components
        (Label                          lbJoinOneEnd)
        (SubLayout                      LayJoinOneEndContent)
    )

    (Resources
        (lbJoinOneEnd.Label             "Join one Profile End to Profile")
        (lbJoinOneEnd.AttachLeft        True)
        (lbJoinOneEnd.AttachTop         True)
        (lbJoinOneEnd.TopOffset         0)
        (lbJoinOneEnd.BottomOffset      5)
        (lbJoinOneEnd.LeftOffset        0)
        (lbJoinOneEnd.RightOffset       0)
        (lbJoinOneEnd.FontStyle         8)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                lbJoinOneEnd
                LayJoinOneEndContent
            )
        )
    )
)

(Layout LayJoinOneEndContent
    (Components
        (CheckButton                    cbTJoint)
        (CheckButton                    cbTOverlap)
    )

    (Resources
        (cbTJoint.Bitmap                "afx_dia_joints_t_48x48.png")
        (cbTJoint.HelpText              "Define T-joint.")
        (cbTJoint.ButtonStyle           2)
        (cbTJoint.ModalOveride          2)
        (cbTJoint.AttachLeft            True)
        (cbTJoint.AttachTop             True)
        (cbTJoint.KeyboardInput         True)
        (cbTJoint.TopOffset             0)
        (cbTJoint.BottomOffset          3)
        (cbTJoint.LeftOffset            0)
        (cbTJoint.RightOffset           3)
        (cbTOverlap.Bitmap              "afx_dia_joints_t_overlapp_48x48.png")
        (cbTOverlap.HelpText            "Define T-joint with overlap.")
        (cbTOverlap.ButtonStyle         2)
        (cbTOverlap.ModalOveride        2)
        (cbTOverlap.AttachLeft          True)
        (cbTOverlap.AttachTop           True)
        (cbTOverlap.KeyboardInput       True)
        (cbTOverlap.TopOffset           0)
        (cbTOverlap.BottomOffset        3)
        (cbTOverlap.LeftOffset          0)
        (cbTOverlap.RightOffset         3)
        (.AttachLeft                    True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 0 1)
                cbTJoint
                cbTOverlap
            )
        )
    )
)

(Layout LayoutJoinEndToSurf
    (Components
        (Label                          lbJoinSurfIntersect)
        (SubLayout                      LayoutJoinEndToSurfContent)
    )

    (Resources
        (lbJoinSurfIntersect.Label      "Join one Profile End to Surface")
        (lbJoinSurfIntersect.AttachLeft True)
        (lbJoinSurfIntersect.AttachTop  True)
        (lbJoinSurfIntersect.TopOffset  0)
        (lbJoinSurfIntersect.BottomOffset 5)
        (lbJoinSurfIntersect.LeftOffset 0)
        (lbJoinSurfIntersect.RightOffset 0)
        (lbJoinSurfIntersect.FontStyle  8)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                lbJoinSurfIntersect
                LayoutJoinEndToSurfContent
            )
        )
    )
)

(Layout LayoutJoinEndToSurfContent
    (Components
        (CheckButton                    cbJoinSelSurf)
        (CheckButton                    cbJoinselSurfStraight)
        (CheckButton                    cbJointSelSurfIntersectStraight)
    )

    (Resources
        (cbJoinSelSurf.Bitmap           "afx_dia_joints_sel_surface_48x48.png")
        (cbJoinSelSurf.HelpText         "Define joint to selected surface.")
        (cbJoinSelSurf.ButtonStyle      2)
        (cbJoinSelSurf.ModalOveride     2)
        (cbJoinSelSurf.AttachLeft       True)
        (cbJoinSelSurf.AttachTop        True)
        (cbJoinSelSurf.KeyboardInput    True)
        (cbJoinSelSurf.TopOffset        0)
        (cbJoinSelSurf.BottomOffset     3)
        (cbJoinSelSurf.LeftOffset       0)
        (cbJoinSelSurf.RightOffset      3)
        (cbJoinselSurfStraight.Bitmap   "afx_dia_joints_sel_surface_straight_48x48.png")
        (cbJoinselSurfStraight.HelpText "Define joint to selected surface with normal cut.")
        (cbJoinselSurfStraight.ButtonStyle 2)
        (cbJoinselSurfStraight.ModalOveride 2)
        (cbJoinselSurfStraight.AttachLeft True)
        (cbJoinselSurfStraight.AttachTop True)
        (cbJoinselSurfStraight.KeyboardInput True)
        (cbJoinselSurfStraight.TopOffset 0)
        (cbJoinselSurfStraight.BottomOffset 3)
        (cbJoinselSurfStraight.LeftOffset 0)
        (cbJoinselSurfStraight.RightOffset 3)
        (cbJointSelSurfIntersectStraight.Bitmap "afx_dia_joints_sel_surface_straight_intersec_48x48.png")
        (cbJointSelSurfIntersectStraight.HelpText "Define joint to selected surface with normal cut along intersection line.")
        (cbJointSelSurfIntersectStraight.ButtonStyle 2)
        (cbJointSelSurfIntersectStraight.ModalOveride 2)
        (cbJointSelSurfIntersectStraight.AttachLeft True)
        (cbJointSelSurfIntersectStraight.AttachTop True)
        (cbJointSelSurfIntersectStraight.KeyboardInput True)
        (cbJointSelSurfIntersectStraight.TopOffset 0)
        (cbJointSelSurfIntersectStraight.BottomOffset 3)
        (cbJointSelSurfIntersectStraight.LeftOffset 0)
        (cbJointSelSurfIntersectStraight.RightOffset 3)
        (.AttachLeft                    True)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 1)
                cbJoinSelSurf
                cbJoinselSurfStraight
                cbJointSelSurfIntersectStraight
            )
        )
    )
)

(Layout LayoutJoinDatums
    (Components
        (Label                          lbJoinDatums)
        (SubLayout                      LayoutJoinDatumsContent)
    )

    (Resources
        (lbJoinDatums.Label             "Join Datums")
        (lbJoinDatums.AttachLeft        True)
        (lbJoinDatums.AttachTop         True)
        (lbJoinDatums.TopOffset         0)
        (lbJoinDatums.BottomOffset      5)
        (lbJoinDatums.LeftOffset        0)
        (lbJoinDatums.RightOffset       0)
        (lbJoinDatums.FontStyle         8)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                lbJoinDatums
                LayoutJoinDatumsContent
            )
        )
    )
)

(Layout LayoutJoinDatumsContent
    (Components
        (CheckButton                    cbOffsetCysToCsys)
        (CheckButton                    cbOffsetCsysToPlane)
        (CheckButton                    cbOffsetPntToPnt)
    )

    (Resources
        (cbOffsetCysToCsys.Bitmap       "afx_dia_joints_offsetcsys_to_csys_48x48.png")
        (cbOffsetCysToCsys.HelpText     "Define offset csys to csys joint.")
        (cbOffsetCysToCsys.ButtonStyle  2)
        (cbOffsetCysToCsys.ModalOveride 2)
        (cbOffsetCysToCsys.AttachLeft   True)
        (cbOffsetCysToCsys.AttachTop    True)
        (cbOffsetCysToCsys.KeyboardInput True)
        (cbOffsetCysToCsys.TopOffset    0)
        (cbOffsetCysToCsys.BottomOffset 3)
        (cbOffsetCysToCsys.LeftOffset   0)
        (cbOffsetCysToCsys.RightOffset  3)
        (cbOffsetCsysToPlane.Bitmap     "afx_dia_joints_offsetcsys_to_plane_48x48.png")
        (cbOffsetCsysToPlane.HelpText   "Define offset csys to plane joint.")
        (cbOffsetCsysToPlane.ButtonStyle 2)
        (cbOffsetCsysToPlane.ModalOveride 2)
        (cbOffsetCsysToPlane.AttachLeft True)
        (cbOffsetCsysToPlane.AttachTop  True)
        (cbOffsetCsysToPlane.KeyboardInput True)
        (cbOffsetCsysToPlane.TopOffset  0)
        (cbOffsetCsysToPlane.BottomOffset 3)
        (cbOffsetCsysToPlane.LeftOffset 0)
        (cbOffsetCsysToPlane.RightOffset 3)
        (cbOffsetPntToPnt.Bitmap        "afx_dia_joints_pnt_to_pnt_48x48.png")
        (cbOffsetPntToPnt.HelpText      "Define offset point to point joint.")
        (cbOffsetPntToPnt.ButtonStyle   2)
        (cbOffsetPntToPnt.ModalOveride  2)
        (cbOffsetPntToPnt.AttachLeft    True)
        (cbOffsetPntToPnt.AttachTop     True)
        (cbOffsetPntToPnt.KeyboardInput True)
        (cbOffsetPntToPnt.TopOffset     0)
        (cbOffsetPntToPnt.BottomOffset  3)
        (cbOffsetPntToPnt.LeftOffset    0)
        (cbOffsetPntToPnt.RightOffset   3)
        (.AttachLeft                    True)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 1)
                cbOffsetCysToCsys
                cbOffsetCsysToPlane
                cbOffsetPntToPnt
            )
        )
    )
)

(Layout LayoutOffset
    (Components
        (CheckButton                    cbWithOffset)
        (Label                          lbImgDim1)
        (InputPanel                     ipDim1)
        (Label                          lbImgDim2)
        (InputPanel                     ipDim2)
    )

    (Resources
        (cbWithOffset.Label             "With offset")
        (cbWithOffset.ModalOveride      2)
        (cbWithOffset.AttachLeft        True)
        (cbWithOffset.KeyboardInput     True)
        (cbWithOffset.TopOffset         0)
        (cbWithOffset.BottomOffset      5)
        (cbWithOffset.LeftOffset        0)
        (cbWithOffset.RightOffset       0)
        (lbImgDim1.Bitmap               "afx_dia_dimension_1_29x13.png")
        (lbImgDim1.AttachLeft           True)
        (lbImgDim1.TopOffset            0)
        (lbImgDim1.BottomOffset         0)
        (lbImgDim1.LeftOffset           0)
        (lbImgDim1.RightOffset          3)
        (ipDim1.Columns                 4)
        (ipDim1.ModalOveride            1)
        (ipDim1.TopOffset               0)
        (ipDim1.BottomOffset            0)
        (ipDim1.LeftOffset              0)
        (ipDim1.RightOffset             10)
        (ipDim1.AutoHighlight           True)
        (lbImgDim2.Bitmap               "afx_dia_dimension_2_29x13.png")
        (lbImgDim2.TopOffset            0)
        (lbImgDim2.BottomOffset         0)
        (lbImgDim2.LeftOffset           0)
        (lbImgDim2.RightOffset          3)
        (ipDim2.Columns                 4)
        (ipDim2.ModalOveride            1)
        (ipDim2.TopOffset               0)
        (ipDim2.BottomOffset            0)
        (ipDim2.LeftOffset              0)
        (ipDim2.RightOffset             0)
        (ipDim2.AutoHighlight           True)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                cbWithOffset
                (Grid (Rows 1) (Cols 0 1 0 0)
                    lbImgDim1
                    ipDim1
                    lbImgDim2
                    ipDim2
                )
            )
        )
    )
)

(Layout LayoutReferences
    (Components
        (Label                          lbHeaderReferences)
        (SubLayout                      LayoutReferencesContent)
    )

    (Resources
        (lbHeaderReferences.Label       "References")
        (lbHeaderReferences.AttachLeft  True)
        (lbHeaderReferences.AttachTop   True)
        (lbHeaderReferences.TopOffset   0)
        (lbHeaderReferences.BottomOffset 5)
        (lbHeaderReferences.LeftOffset  0)
        (lbHeaderReferences.RightOffset 0)
        (lbHeaderReferences.FontStyle   8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                lbHeaderReferences
                LayoutReferencesContent
            )
        )
    )
)

(Layout LayoutReferencesContent
    (Components
        (SubLayout                      LayRef1)
        (Table                          tblRef1)
        (SubLayout                      LayRef2)
        (Table                          tblRef2)
    )

    (Resources
        (tblRef1.Columns                10)
        (tblRef1.VisibleRows            1)
        (tblRef1.ModalOveride           2)
        (tblRef1.MinColumns             10)
        (tblRef1.BackgroundColor        31456491)
        (tblRef1.TopOffset              0)
        (tblRef1.BottomOffset           5)
        (tblRef1.LeftOffset             5)
        (tblRef1.RightOffset            0)
        (tblRef1.ScrollBarPosition      5)
        (tblRef1.RowNames               "row_1")
        (tblRef1.ColumnNames            "column_1")
        (tblRef1.ScrollBarsWhenNeeded   False)
        (tblRef1.ColumnWidths           25)
        (tblRef2.Columns                10)
        (tblRef2.VisibleRows            1)
        (tblRef2.ModalOveride           2)
        (tblRef2.MinColumns             10)
        (tblRef2.BackgroundColor        31456491)
        (tblRef2.TopOffset              0)
        (tblRef2.BottomOffset           5)
        (tblRef2.LeftOffset             5)
        (tblRef2.RightOffset            0)
        (tblRef2.ScrollBarPosition      5)
        (tblRef2.RowNames               "row_1")
        (tblRef2.ColumnNames            "column_1")
        (tblRef2.ScrollBarsWhenNeeded   False)
        (tblRef2.ColumnWidths           25)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 1 1 1) (Cols 1)
                LayRef1
                tblRef1
                LayRef2
                tblRef2
            )
        )
    )
)

(Layout LayRef1
    (Components
        (Label                          lbRef1)
        (Label                          lbRef1_1)
        (Label                          lbRef1_2)
        (Label                          lbRef1_3)
    )

    (Resources
        (lbRef1.Label                   "First profile")
        (lbRef1.AttachLeft              True)
        (lbRef1.AttachTop               True)
        (lbRef1.TopOffset               0)
        (lbRef1.BottomOffset            5)
        (lbRef1.LeftOffset              5)
        (lbRef1.RightOffset             0)
        (lbRef1_1.Label                 "Adjoining profile")
        (lbRef1_1.Visible               False)
        (lbRef1_1.AttachLeft            True)
        (lbRef1_1.AttachTop             True)
        (lbRef1_1.TopOffset             0)
        (lbRef1_1.BottomOffset          5)
        (lbRef1_1.LeftOffset            5)
        (lbRef1_1.RightOffset           0)
        (lbRef1_2.Label                 "Offset coordinate system")
        (lbRef1_2.Visible               False)
        (lbRef1_2.AttachLeft            True)
        (lbRef1_2.AttachTop             True)
        (lbRef1_2.TopOffset             0)
        (lbRef1_2.BottomOffset          5)
        (lbRef1_2.LeftOffset            5)
        (lbRef1_2.RightOffset           0)
        (lbRef1_3.Label                 "Offset datum point")
        (lbRef1_3.Visible               False)
        (lbRef1_3.AttachLeft            True)
        (lbRef1_3.AttachTop             True)
        (lbRef1_3.TopOffset             0)
        (lbRef1_3.BottomOffset          5)
        (lbRef1_3.LeftOffset            5)
        (lbRef1_3.RightOffset           0)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 1 1)
                lbRef1
                lbRef1_1
                lbRef1_2
                lbRef1_3
            )
        )
    )
)


(Layout LayRef2
    (Components
        (Label                          lbRef2)
        (Label                          lbRef2_1)
        (Label                          lbRef2_2)
        (Label                          lbRef2_3)
        (Label                          lbRef2_4)
        (Label                          lbRef2_5)
    )

    (Resources
        (lbRef2.Label                   "Second profile")
        (lbRef2.AttachLeft              True)
        (lbRef2.AttachTop               True)
        (lbRef2.TopOffset               0)
        (lbRef2.BottomOffset            5)
        (lbRef2.LeftOffset              5)
        (lbRef2.RightOffset             0)
        (lbRef2_1.Label                 "Unchanged profile")
        (lbRef2_1.Visible               False)
        (lbRef2_1.AttachLeft            True)
        (lbRef2_1.AttachTop             True)
        (lbRef2_1.TopOffset             0)
        (lbRef2_1.BottomOffset          5)
        (lbRef2_1.LeftOffset            5)
        (lbRef2_1.RightOffset           0)
        (lbRef2_2.Label                 "Attachment surface")
        (lbRef2_2.Visible               False)
        (lbRef2_2.AttachLeft            True)
        (lbRef2_2.AttachTop             True)
        (lbRef2_2.TopOffset             0)
        (lbRef2_2.BottomOffset          5)
        (lbRef2_2.LeftOffset            5)
        (lbRef2_2.RightOffset           0)
        (lbRef2_3.Label                 "Coordinate system")
        (lbRef2_3.Visible               False)
        (lbRef2_3.AttachLeft            True)
        (lbRef2_3.AttachTop             True)
        (lbRef2_3.TopOffset             0)
        (lbRef2_3.BottomOffset          5)
        (lbRef2_3.LeftOffset            5)
        (lbRef2_3.RightOffset           0)
        (lbRef2_4.Label                 "Datum plane or planar surface")
        (lbRef2_4.Visible               False)
        (lbRef2_4.AttachLeft            True)
        (lbRef2_4.AttachTop             True)
        (lbRef2_4.TopOffset             0)
        (lbRef2_4.BottomOffset          5)
        (lbRef2_4.LeftOffset            5)
        (lbRef2_4.RightOffset           0)
        (lbRef2_5.Label                 "Datum point")
        (lbRef2_5.Visible               False)
        (lbRef2_5.AttachLeft            True)
        (lbRef2_5.AttachTop             True)
        (lbRef2_5.TopOffset             0)
        (lbRef2_5.BottomOffset          5)
        (lbRef2_5.LeftOffset            5)
        (lbRef2_5.RightOffset           0)
        (.AttachLeft                    True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 1 1 1 1)
                lbRef2
                lbRef2_1
                lbRef2_2
                lbRef2_3
                lbRef2_4
                lbRef2_5
            )
        )
    )
)


(Layout LayoutCommitBar
    (Components
        (PushButton                     pb_apply)
        (PushButton                     pb_OK)
        (PushButton                     pb_Cancel)
    )

    (Resources
        (pb_apply.Label                 "Repeat")
        (pb_apply.Columns               5)
        (pb_apply.ButtonStyle           2)
        (pb_apply.ModalOveride          2)
        (pb_apply.AttachLeft            True)
        (pb_apply.KeyboardInput         True)
        (pb_apply.TopOffset             0)
        (pb_apply.BottomOffset          0)
        (pb_apply.LeftOffset            0)
        (pb_apply.RightOffset           40)
        (pb_OK.Label                    "OK")
        (pb_OK.Columns                  5)
        (pb_OK.ButtonStyle              2)
        (pb_OK.ModalOveride             2)
        (pb_OK.AttachRight              True)
        (pb_OK.KeyboardInput            True)
        (pb_OK.TopOffset                0)
        (pb_OK.BottomOffset             0)
        (pb_OK.LeftOffset               0)
        (pb_OK.RightOffset              8)
        (pb_Cancel.Label                "Cancel")
        (pb_Cancel.Columns              5)
        (pb_Cancel.ButtonStyle          2)
        (pb_Cancel.ModalOveride         2)
        (pb_Cancel.AttachRight          True)
        (pb_Cancel.KeyboardInput        True)
        (pb_Cancel.TopOffset            0)
        (pb_Cancel.BottomOffset         0)
        (pb_Cancel.LeftOffset           0)
        (pb_Cancel.RightOffset          0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1) (Cols 1 1 0)
                pb_apply
                pb_OK
                pb_Cancel
            )
        )
    )
)
