(Dialog screw_dialog
    (Components
        (SubLayout                      main_layout)
        (SubLayout                      hole_layout)
    )

    (Resources
        (.Label                         "Screw Fastener Definition")
        (.Focus                         "screwtype_comboex")
        (.StartLocation                 3)
        (.Resizeable                    False)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.DefaultButton                 "pb_OK")
        (.SystemMenuButton              True)
        (.TitleBarImage                 "buw_titlebar.png")
        (.Layout
            (Grid (Rows 1) (Cols 1 1)
                main_layout
                hole_layout
            )
        )
    )
)

(Layout main_layout
    (Components
        (SubLayout                      component_layout)
        (SubLayout                      expand_layout)
        (SubLayout                      expand_preview_layout)
        (SubLayout                      preview_layout)
        (SubLayout                      footer_layout)
    )

    (Resources
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                (Grid (Rows 1) (Cols 1 1)
                    (Grid (Rows 0 1 0) (Cols 1)
                        component_layout
                        expand_preview_layout
                        preview_layout
                    )
                    expand_layout
                )
                footer_layout
            )
        )
    )
)

(Layout component_layout
    (Components
        (SubLayout                      standard_layout)
        (SubLayout                      screw_layout)
        (SubLayout                      insert_layout)
        (SubLayout                      nut_layout)
        (SubLayout                      asm_layout)
    )

    (Resources
        (.Mapped                        False)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.Alignment                     1)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 0 1 1 1) (Cols 1)
                standard_layout
                screw_layout
                insert_layout
                nut_layout
                asm_layout
            )
        )
    )
)

(Layout standard_layout
    (Components
        (Label                          standard_txt)
        (CheckButton                    standard_dummy_check)
        (OptionMenu                     standard_combo)
        (PushButton                     save_fastener)
        (PushButton                     open_fastener)
        (PushButton                     pick_fastener)
    )

    (Resources
        (standard_txt.Label             "Catalog")
        (standard_txt.Columns           6)
        (standard_txt.AttachLeft        True)
        (standard_txt.Alignment         1)
        (standard_txt.TopOffset         0)
        (standard_txt.BottomOffset      0)
        (standard_txt.LeftOffset        0)
        (standard_txt.RightOffset       0)
        (standard_txt.FontStyle         8)
        (standard_dummy_check.Visible   False)
        (standard_dummy_check.Mapped    True)
        (standard_dummy_check.AttachLeft True)
        (standard_dummy_check.TopOffset 0)
        (standard_dummy_check.BottomOffset 0)
        (standard_dummy_check.LeftOffset 10)
        (standard_dummy_check.RightOffset 10)
        (standard_combo.Columns         0)
        (standard_combo.Names           "def1")
        (standard_combo.Labels          "-")
        (standard_combo.MinColumns      7)
        (standard_combo.TopOffset       0)
        (standard_combo.BottomOffset    0)
        (standard_combo.LeftOffset      0)
        (standard_combo.RightOffset     13)
        (standard_combo.MinDouble       0.000000)
        (standard_combo.SizeByContents  True)
        (save_fastener.Bitmap           "save16x16")
        (save_fastener.HelpText         "Save fastener definition to file.")
        (save_fastener.ButtonStyle      3)
        (save_fastener.AttachRight      True)
        (save_fastener.TopOffset        0)
        (save_fastener.BottomOffset     0)
        (save_fastener.LeftOffset       0)
        (save_fastener.RightOffset      0)
        (open_fastener.Bitmap           "open16x16")
        (open_fastener.HelpText         "Open a fastener definition from file.")
        (open_fastener.ButtonStyle      3)
        (open_fastener.AttachRight      True)
        (open_fastener.TopOffset        0)
        (open_fastener.BottomOffset     0)
        (open_fastener.LeftOffset       0)
        (open_fastener.RightOffset      0)
        (pick_fastener.Bitmap           "sel_pick16x16")
        (pick_fastener.HelpText         "Select a fastener from current assmebly to copy its definition.")
        (pick_fastener.ButtonStyle      3)
        (pick_fastener.AttachRight      True)
        (pick_fastener.TopOffset        0)
        (pick_fastener.BottomOffset     0)
        (pick_fastener.LeftOffset       0)
        (pick_fastener.RightOffset      0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     16)
        (.BottomOffset                  10)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1) (Cols 0 0 1 1 0 0)
                standard_txt
                standard_dummy_check
                standard_combo
                pick_fastener
                open_fastener
                save_fastener
            )
        )
    )
)

(Layout screw_layout
    (Components
        (Label                          screw_txt)
        (Label                          steigung_txt)
        (CheckButton                    screw_check)
        (OptionMenu                     screwtype_comboex)
        (Label                          thread_txt)
        (CheckButton                    screw_dxl_dummy_check)
        (SubLayout                      screw_dxl_layout)
        (Label                          washer_side1_txt)
        (CheckButton                    screwspringwasher_check)
        (OptionMenu                     screwspringwasher_comboex)
        (CheckButton                    screwwasher_check)
        (OptionMenu                     screwwasher_comboex)
        (Separator                      screw_separator)
        (Separator                      Separator4)
    )

    (Resources
        (screw_txt.Label                "Screw")
        (screw_txt.Columns              6)
        (screw_txt.AttachRight          True)
        (screw_txt.Alignment            1)
        (screw_txt.TopOffset            0)
        (screw_txt.BottomOffset         0)
        (screw_txt.LeftOffset           0)
        (screw_txt.RightOffset          0)
        (screw_txt.FontStyle            8)
        (steigung_txt.Label             "...")
        (steigung_txt.Columns           6)
        (steigung_txt.Mapped            True)
        (steigung_txt.AttachRight       True)
        (steigung_txt.Alignment         1)
        (steigung_txt.Resizeable        True)
        (steigung_txt.TopOffset         5)
        (steigung_txt.BottomOffset      0)
        (steigung_txt.LeftOffset        0)
        (steigung_txt.RightOffset       0)
        (screw_check.Visible            False)
        (screw_check.Mapped             True)
        (screw_check.AttachLeft         True)
        (screw_check.TopOffset          0)
        (screw_check.BottomOffset       0)
        (screw_check.LeftOffset         10)
        (screw_check.RightOffset        10)
        (screwtype_comboex.Columns      20)
        (screwtype_comboex.Names        "def1")
        (screwtype_comboex.Labels       "-")
        (screwtype_comboex.ItemImage    "32x32.png")
        (screwtype_comboex.MinColumns   15)
        (screwtype_comboex.TopOffset    0)
        (screwtype_comboex.BottomOffset 0)
        (screwtype_comboex.LeftOffset   0)
        (screwtype_comboex.RightOffset  0)
        (screwtype_comboex.MaxColumns   15)
        (thread_txt.Label               "Thread")
        (thread_txt.Columns             6)
        (thread_txt.AttachLeft          True)
        (thread_txt.AttachRight         True)
        (thread_txt.Alignment           1)
        (thread_txt.TopOffset           17)
        (thread_txt.BottomOffset        0)
        (thread_txt.LeftOffset          0)
        (thread_txt.RightOffset         0)
        (thread_txt.FontStyle           8)
        (screw_dxl_dummy_check.Visible  False)
        (screw_dxl_dummy_check.AttachLeft True)
        (screw_dxl_dummy_check.TopOffset 10)
        (screw_dxl_dummy_check.BottomOffset 0)
        (screw_dxl_dummy_check.LeftOffset 10)
        (screw_dxl_dummy_check.RightOffset 10)
        (washer_side1_txt.Label         "Side 1
Washers")
        (washer_side1_txt.Columns       6)
        (washer_side1_txt.AttachRight   True)
        (washer_side1_txt.AttachTop     True)
        (washer_side1_txt.Alignment     1)
        (washer_side1_txt.TopOffset     22)
        (washer_side1_txt.BottomOffset  0)
        (washer_side1_txt.LeftOffset    0)
        (washer_side1_txt.RightOffset   0)
        (washer_side1_txt.FontStyle     8)
        (screwspringwasher_check.AttachLeft True)
        (screwspringwasher_check.TopOffset 10)
        (screwspringwasher_check.BottomOffset 0)
        (screwspringwasher_check.LeftOffset 10)
        (screwspringwasher_check.RightOffset 10)
        (screwspringwasher_comboex.Columns 20)
        (screwspringwasher_comboex.AttachTop True)
        (screwspringwasher_comboex.Names "def1")
        (screwspringwasher_comboex.Labels "-")
        (screwspringwasher_comboex.ItemImage "16x32.png")
        (screwspringwasher_comboex.MinColumns 15)
        (screwspringwasher_comboex.TopOffset 10)
        (screwspringwasher_comboex.BottomOffset 0)
        (screwspringwasher_comboex.LeftOffset 0)
        (screwspringwasher_comboex.RightOffset 0)
        (screwspringwasher_comboex.MaxColumns 15)
        (screwwasher_check.AttachLeft   True)
        (screwwasher_check.TopOffset    10)
        (screwwasher_check.BottomOffset 0)
        (screwwasher_check.LeftOffset   10)
        (screwwasher_check.RightOffset  10)
        (screwwasher_comboex.Columns    20)
        (screwwasher_comboex.Names      "def1")
        (screwwasher_comboex.Labels     "-")
        (screwwasher_comboex.ItemImage  "16x32.png")
        (screwwasher_comboex.MinColumns 15)
        (screwwasher_comboex.TopOffset  10)
        (screwwasher_comboex.BottomOffset 0)
        (screwwasher_comboex.LeftOffset 0)
        (screwwasher_comboex.RightOffset 0)
        (screwwasher_comboex.MaxColumns 15)
        (screw_separator.TopOffset      0)
        (screw_separator.BottomOffset   10)
        (screw_separator.LeftOffset     0)
        (screw_separator.RightOffset    0)
        (Separator4.TopOffset           0)
        (Separator4.BottomOffset        0)
        (Separator4.LeftOffset          0)
        (Separator4.RightOffset         0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 0) (Cols 1)
                screw_separator
                (Grid (Rows 0) (Cols 0 0 1)
                    (Grid (Rows 0 0 0 0) (Cols 0)
                        screw_txt
                        steigung_txt
                        thread_txt
                        washer_side1_txt
                    )
                    Separator4
                    (Grid (Rows 0 0 0 0) (Cols 0 1)
                        screw_check
                        screwtype_comboex
                        screw_dxl_dummy_check
                        screw_dxl_layout
                        screwspringwasher_check
                        screwspringwasher_comboex
                        screwwasher_check
                        screwwasher_comboex
                    )
                )
            )
        )
    )
)

(Layout screw_dxl_layout
    (Components
        (OptionMenu                     screwdm_combo)
        (PushButton                     screwautolength_button)
        (Label                          screwlaenge_txt)
        (OptionMenu                     screwlaenge_combo)
        (PushButton                     measurediameter_button)
        (CheckButton                    screwautolength_check)
    )

    (Resources
        (screwdm_combo.Columns          5)
        (screwdm_combo.TopOffset        0)
        (screwdm_combo.BottomOffset     0)
        (screwdm_combo.LeftOffset       0)
        (screwdm_combo.RightOffset      0)
        (screwautolength_button.Bitmap  "ifx_scr_autolength.png")
        (screwautolength_button.HelpText "Set length automatically")
        (screwautolength_button.ButtonStyle 2)
        (screwautolength_button.Alignment 2)
        (screwautolength_button.TopOffset 0)
        (screwautolength_button.BottomOffset 0)
        (screwautolength_button.LeftOffset 6)
        (screwautolength_button.RightOffset 0)
        (screwlaenge_txt.Label          "x")
        (screwlaenge_txt.TopOffset      0)
        (screwlaenge_txt.BottomOffset   0)
        (screwlaenge_txt.LeftOffset     3)
        (screwlaenge_txt.RightOffset    5)
        (screwlaenge_combo.Columns      4)
        (screwlaenge_combo.PopupMenu    "screw_popup")
        (screwlaenge_combo.TopOffset    0)
        (screwlaenge_combo.BottomOffset 0)
        (screwlaenge_combo.LeftOffset   0)
        (screwlaenge_combo.RightOffset  0)
        (measurediameter_button.Bitmap  "ifx_scr_measurediameter.png")
        (measurediameter_button.HelpText "Measure a diameter")
        (measurediameter_button.ButtonStyle 2)
        (measurediameter_button.Alignment 2)
        (measurediameter_button.TopOffset 0)
        (measurediameter_button.BottomOffset 0)
        (measurediameter_button.LeftOffset 6)
        (measurediameter_button.RightOffset 6)
        (screwautolength_check.Bitmap   "ifx_scr_autolengthauto_ok.png")
        (screwautolength_check.HelpText "Permanently set length automatically")
        (screwautolength_check.ButtonStyle 2)
        (screwautolength_check.AttachRight True)
        (screwautolength_check.TopOffset 0)
        (screwautolength_check.BottomOffset 0)
        (screwautolength_check.LeftOffset 5)
        (screwautolength_check.RightOffset 0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.TopOffset                     10)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1 0 0 1 0 1)
                screwdm_combo
                measurediameter_button
                screwlaenge_txt
                screwlaenge_combo
                screwautolength_button
                screwautolength_check
            )
        )
    )
)

(Layout insert_layout
    (Components
        (Label                          insert_txt)
        (CheckButton                    insert_check)
        (OptionMenu                     inserttype_comboex)
        (Separator                      insert_separator)
        (CheckButton                    insertinsubasm_check)
        (Label                          insertinsubasm_txt)
        (Separator                      Separator8)
    )

    (Resources
        (insert_txt.Label               "Insert")
        (insert_txt.Columns             6)
        (insert_txt.AttachRight         True)
        (insert_txt.AttachTop           True)
        (insert_txt.AttachBottom        True)
        (insert_txt.Alignment           1)
        (insert_txt.TopOffset           0)
        (insert_txt.BottomOffset        0)
        (insert_txt.LeftOffset          0)
        (insert_txt.RightOffset         0)
        (insert_txt.FontStyle           8)
        (insert_check.AttachRight       True)
        (insert_check.TopOffset         0)
        (insert_check.BottomOffset      0)
        (insert_check.LeftOffset        10)
        (insert_check.RightOffset       10)
        (inserttype_comboex.Columns     20)
        (inserttype_comboex.VisibleRows 2)
        (inserttype_comboex.AttachRight False)
        (inserttype_comboex.Names       "def1")
        (inserttype_comboex.Labels      "-")
        (inserttype_comboex.ItemImage   "32x32.png")
        (inserttype_comboex.TopOffset   0)
        (inserttype_comboex.BottomOffset 0)
        (inserttype_comboex.LeftOffset  0)
        (inserttype_comboex.RightOffset 0)
        (inserttype_comboex.Gravity     1)
        (inserttype_comboex.ImageWidth  32)
        (inserttype_comboex.ImageHeight 32)
        (insert_separator.TopOffset     10)
        (insert_separator.BottomOffset  10)
        (insert_separator.LeftOffset    0)
        (insert_separator.RightOffset   0)
        (insertinsubasm_check.AttachLeft True)
        (insertinsubasm_check.TopOffset 5)
        (insertinsubasm_check.BottomOffset 0)
        (insertinsubasm_check.LeftOffset 0)
        (insertinsubasm_check.RightOffset 0)
        (insertinsubasm_txt.Visible     False)
        (insertinsubasm_txt.Columns     6)
        (insertinsubasm_txt.AttachLeft  True)
        (insertinsubasm_txt.AttachRight True)
        (insertinsubasm_txt.Alignment   1)
        (insertinsubasm_txt.TopOffset   10)
        (insertinsubasm_txt.BottomOffset 0)
        (insertinsubasm_txt.LeftOffset  0)
        (insertinsubasm_txt.RightOffset 0)
        (insertinsubasm_txt.FontStyle   8)
        (Separator8.Visible             False)
        (Separator8.Orientation         True)
        (Separator8.TopOffset           0)
        (Separator8.BottomOffset        0)
        (Separator8.LeftOffset          0)
        (Separator8.RightOffset         0)
        (.Visible                       False)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                insert_separator
                (Grid (Rows 1) (Cols 1 1 1)
                    (Grid (Rows 1 1) (Cols 1)
                        insert_txt
                    )
                    Separator8
                    (Grid (Rows 0 1) (Cols 1 0)
                        insert_check
                        inserttype_comboex
                        insertinsubasm_txt
                        insertinsubasm_check
                    )
                )
            )
        )
    )
)

(Layout nut_layout
    (Components
        (Label                          nutwashers_txt)
        (CheckButton                    nutwasher_check)
        (OptionMenu                     nutwasher_comboex)
        (Label                          nut_txt)
        (CheckButton                    nutspringwasher_check)
        (OptionMenu                     nutspringwasher_comboex)
        (CheckButton                    nut_check)
        (OptionMenu                     nuttype_comboex)
        (Separator                      nut_separator)
        (CheckButton                    nutinsubasm_check)
        (Label                          nutinsubasm_txt)
        (Separator                      Separator7)
    )

    (Resources
        (nutwashers_txt.Label           "Side 2
Washers")
        (nutwashers_txt.Columns         6)
        (nutwashers_txt.AttachRight     True)
        (nutwashers_txt.AttachTop       True)
        (nutwashers_txt.Alignment       1)
        (nutwashers_txt.TopOffset       5)
        (nutwashers_txt.BottomOffset    0)
        (nutwashers_txt.LeftOffset      0)
        (nutwashers_txt.RightOffset     0)
        (nutwashers_txt.FontStyle       8)
        (nutwasher_check.AttachLeft     True)
        (nutwasher_check.TopOffset      0)
        (nutwasher_check.BottomOffset   0)
        (nutwasher_check.LeftOffset     10)
        (nutwasher_check.RightOffset    10)
        (nutwasher_comboex.Columns      20)
        (nutwasher_comboex.Names        "def1")
        (nutwasher_comboex.Labels       "-")
        (nutwasher_comboex.ItemImage    "16x32.png")
        (nutwasher_comboex.TopOffset    0)
        (nutwasher_comboex.BottomOffset 0)
        (nutwasher_comboex.LeftOffset   0)
        (nutwasher_comboex.RightOffset  0)
        (nut_txt.Label                  "Nut")
        (nut_txt.Columns                6)
        (nut_txt.AttachLeft             True)
        (nut_txt.AttachRight            True)
        (nut_txt.AttachTop              True)
        (nut_txt.AttachBottom           True)
        (nut_txt.Alignment              1)
        (nut_txt.TopOffset              10)
        (nut_txt.BottomOffset           0)
        (nut_txt.LeftOffset             0)
        (nut_txt.RightOffset            0)
        (nut_txt.FontStyle              8)
        (nutspringwasher_check.TopOffset 10)
        (nutspringwasher_check.BottomOffset 0)
        (nutspringwasher_check.LeftOffset 10)
        (nutspringwasher_check.RightOffset 10)
        (nutspringwasher_comboex.Columns 20)
        (nutspringwasher_comboex.Names  "def1")
        (nutspringwasher_comboex.Labels "-")
        (nutspringwasher_comboex.ItemImage "16x32.png")
        (nutspringwasher_comboex.TopOffset 10)
        (nutspringwasher_comboex.BottomOffset 0)
        (nutspringwasher_comboex.LeftOffset 0)
        (nutspringwasher_comboex.RightOffset 0)
        (nut_check.AttachLeft           True)
        (nut_check.AttachTop            True)
        (nut_check.AttachBottom         True)
        (nut_check.TopOffset            10)
        (nut_check.BottomOffset         0)
        (nut_check.LeftOffset           10)
        (nut_check.RightOffset          10)
        (nuttype_comboex.Columns        20)
        (nuttype_comboex.Names          "def1")
        (nuttype_comboex.Labels         "-")
        (nuttype_comboex.ItemImage      "32x32.png")
        (nuttype_comboex.TopOffset      10)
        (nuttype_comboex.BottomOffset   0)
        (nuttype_comboex.LeftOffset     0)
        (nuttype_comboex.RightOffset    0)
        (nuttype_comboex.Gravity        1)
        (nut_separator.TopOffset        10)
        (nut_separator.BottomOffset     10)
        (nut_separator.LeftOffset       0)
        (nut_separator.RightOffset      0)
        (nutinsubasm_check.AttachLeft   True)
        (nutinsubasm_check.TopOffset    5)
        (nutinsubasm_check.BottomOffset 0)
        (nutinsubasm_check.LeftOffset   0)
        (nutinsubasm_check.RightOffset  0)
        (nutinsubasm_txt.Visible        False)
        (nutinsubasm_txt.Columns        6)
        (nutinsubasm_txt.AttachRight    True)
        (nutinsubasm_txt.Alignment      1)
        (nutinsubasm_txt.TopOffset      10)
        (nutinsubasm_txt.BottomOffset   0)
        (nutinsubasm_txt.LeftOffset     0)
        (nutinsubasm_txt.RightOffset    0)
        (nutinsubasm_txt.FontStyle      8)
        (Separator7.Visible             False)
        (Separator7.TopOffset           10)
        (Separator7.BottomOffset        10)
        (Separator7.LeftOffset          0)
        (Separator7.RightOffset         0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 0 1 1) (Cols 1)
                nut_separator
                (Grid (Rows 0) (Cols 0 1)
                    nutwashers_txt
                    (Grid (Rows 0 0) (Cols 0 1)
                        nutwasher_check
                        nutwasher_comboex
                        nutspringwasher_check
                        nutspringwasher_comboex
                    )
                )
                Separator7
                (Grid (Rows 1 0) (Cols 0 0 1)
                    nut_txt
                    nut_check
                    nuttype_comboex
                    nutinsubasm_txt
                    (Pos 2 3)
                    nutinsubasm_check
                )
            )
        )
    )
)

(Layout asm_layout
    (Components
        (Label                          asm_txt)
        (CheckButton                    asm_dummy_check)
        (OptionMenu                     asm_comboex)
        (Separator                      Separator12)
    )

    (Resources
        (asm_txt.Label                  "Assemble")
        (asm_txt.Columns                6)
        (asm_txt.AttachLeft             True)
        (asm_txt.Alignment              1)
        (asm_txt.TopOffset              0)
        (asm_txt.BottomOffset           0)
        (asm_txt.LeftOffset             0)
        (asm_txt.RightOffset            0)
        (asm_txt.FontStyle              8)
        (asm_dummy_check.Visible        False)
        (asm_dummy_check.Mapped         True)
        (asm_dummy_check.AttachLeft     True)
        (asm_dummy_check.TopOffset      0)
        (asm_dummy_check.BottomOffset   0)
        (asm_dummy_check.LeftOffset     10)
        (asm_dummy_check.RightOffset    10)
        (asm_comboex.Columns            20)
        (asm_comboex.HelpText           "Add fastener to selected assembly.")
        (asm_comboex.Names              "def1")
        (asm_comboex.Labels             "-")
        (asm_comboex.MinColumns         0)
        (asm_comboex.TopOffset          0)
        (asm_comboex.BottomOffset       0)
        (asm_comboex.LeftOffset         0)
        (asm_comboex.RightOffset        0)
        (asm_comboex.MinDouble          0.000000)
        (Separator12.AttachTop          True)
        (Separator12.TopOffset          10)
        (Separator12.BottomOffset       10)
        (Separator12.LeftOffset         0)
        (Separator12.RightOffset        0)
        (.Visible                       False)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    10)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                Separator12
                (Grid (Rows 1) (Cols 0 0 1)
                    asm_txt
                    asm_dummy_check
                    asm_comboex
                )
            )
        )
    )
)

(Layout expand_layout
    (Components
        (Separator                      Separator15)
        (PushButton                     show_hide_holelayout)
    )

    (Resources
        (Separator15.Orientation        True)
        (Separator15.Mapped             True)
        (Separator15.AttachTop          True)
        (Separator15.AttachBottom       True)
        (Separator15.TopOffset          10)
        (Separator15.BottomOffset       10)
        (Separator15.LeftOffset         0)
        (Separator15.RightOffset        0)
        (show_hide_holelayout.Bitmap    "UI ToolBar right image")
        (show_hide_holelayout.HelpText  "Show/Hide Hole Layout")
        (show_hide_holelayout.ButtonStyle 3)
        (show_hide_holelayout.TopOffset 0)
        (show_hide_holelayout.BottomOffset 0)
        (show_hide_holelayout.LeftOffset 0)
        (show_hide_holelayout.RightOffset 0)
        (show_hide_holelayout.FontStyle 8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.Alignment                     1)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1) (Cols 1)
                show_hide_holelayout
                Separator15
            )
        )
    )
)

(Layout expand_preview_layout
    (Components
        (Separator                      Separator2)
        (PushButton                     show_hide_preview_layout)
        (Label                          preview_layout_txt)
    )

    (Resources
        (Separator2.Mapped              True)
        (Separator2.AttachTop           True)
        (Separator2.AttachBottom        True)
        (Separator2.TopOffset           10)
        (Separator2.BottomOffset        10)
        (Separator2.LeftOffset          0)
        (Separator2.RightOffset         0)
        (show_hide_preview_layout.Bitmap "UI ToolBar up image")
        (show_hide_preview_layout.ButtonStyle 3)
        (show_hide_preview_layout.AttachLeft True)
        (show_hide_preview_layout.TopOffset 10)
        (show_hide_preview_layout.BottomOffset 10)
        (show_hide_preview_layout.LeftOffset 10)
        (show_hide_preview_layout.RightOffset 10)
        (show_hide_preview_layout.FontStyle 8)
        (preview_layout_txt.Label       "2D - Preview")
        (preview_layout_txt.AttachLeft  True)
        (preview_layout_txt.TopOffset   0)
        (preview_layout_txt.BottomOffset 0)
        (preview_layout_txt.LeftOffset  0)
        (preview_layout_txt.RightOffset 10)
        (preview_layout_txt.FontStyle   8)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1) (Cols 0 0 1)
                show_hide_preview_layout
                preview_layout_txt
                Separator2
            )
        )
    )
)

(Layout preview_layout
    (Components
        (DrawingArea                    preview_2d)
    )

    (Resources
        (preview_2d.Decorated           False)
        (preview_2d.DrawingWidth        200)
        (preview_2d.DrawingHeight       215)
        (preview_2d.BackgroundColor     255)
        (preview_2d.TopOffset           2)
        (preview_2d.BottomOffset        10)
        (preview_2d.LeftOffset          2)
        (preview_2d.RightOffset         2)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1) (Cols 1)
                preview_2d
            )
        )
    )
)


(Layout footer_layout
    (Components
        (CheckButton                    preview_check)
        (PushButton                     pb_OK)
        (PushButton                     pb_Cancel)
        (Separator                      Separator5)
        (Separator                      Separator3)
    )

    (Resources
        (preview_check.Label            "Preview")
        (preview_check.ButtonStyle      2)
        (preview_check.AttachLeft       True)
        (preview_check.TopOffset        10)
        (preview_check.BottomOffset     10)
        (preview_check.LeftOffset       10)
        (preview_check.RightOffset      0)
        (pb_OK.Label                    "OK")
        (pb_OK.Columns                  5)
        (pb_OK.ButtonStyle              2)
        (pb_OK.AttachRight              True)
        (pb_OK.TopOffset                10)
        (pb_OK.BottomOffset             10)
        (pb_OK.LeftOffset               0)
        (pb_OK.RightOffset              8)
        (pb_Cancel.Label                "Cancel")
        (pb_Cancel.Columns              5)
        (pb_Cancel.ButtonStyle          2)
        (pb_Cancel.AttachRight          True)
        (pb_Cancel.Alignment            1)
        (pb_Cancel.TopOffset            10)
        (pb_Cancel.BottomOffset         10)
        (pb_Cancel.LeftOffset           0)
        (pb_Cancel.RightOffset          10)
        (Separator5.Visible             False)
        (Separator5.Orientation         True)
        (Separator5.TopOffset           10)
        (Separator5.BottomOffset        10)
        (Separator5.LeftOffset          8)
        (Separator5.RightOffset         8)
        (Separator3.AttachBottom        True)
        (Separator3.TopOffset           0)
        (Separator3.BottomOffset        0)
        (Separator3.LeftOffset          0)
        (Separator3.RightOffset         0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.Alignment                     1)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                Separator3
                (Grid (Rows 1) (Cols 1 1 0 0)
                    preview_check
                    Separator5
                    pb_OK
                    pb_Cancel
                )
            )
        )
    )
)

(Layout hole_layout
    (Components
        (SubLayout                      loch_layout)
        (SubLayout                      screwcb_layout)
        (SubLayout                      screw_auto_udf_layout)
        (SubLayout                      nutcb_layout)
        (SubLayout                      nut_auto_udf_layout)
        (SubLayout                      gewbohrtiefe_layout)
        (SubLayout                      footer2_layout)
    )

    (Resources
        (.Label                         "Holes")
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.AttachBottom                  True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 0 0 0 0 0 0 1) (Cols 1)
                loch_layout
                screwcb_layout
                screw_auto_udf_layout
                nutcb_layout
                nut_auto_udf_layout
                gewbohrtiefe_layout
                footer2_layout
            )
        )
    )
)

(Layout loch_layout
    (Components
        (Label                          loch_txt)
        (CheckButton                    loch_check)
        (OptionMenu                     loch_combo)
        (SpinBox                        loch_spin)
        (Label                          loch_hol_txt)
    )

    (Resources
        (loch_txt.Label                 "Hole")
        (loch_txt.AttachLeft            True)
        (loch_txt.AttachTop             True)
        (loch_txt.Alignment             0)
        (loch_txt.TopOffset             0)
        (loch_txt.BottomOffset          0)
        (loch_txt.LeftOffset            0)
        (loch_txt.RightOffset           0)
        (loch_txt.FontStyle             8)
        (loch_check.Visible             False)
        (loch_check.AttachLeft          True)
        (loch_check.AttachTop           True)
        (loch_check.TopOffset           0)
        (loch_check.BottomOffset        10)
        (loch_check.LeftOffset          10)
        (loch_check.RightOffset         10)
        (loch_combo.Columns             0)
        (loch_combo.MinColumns          0)
        (loch_combo.TopOffset           0)
        (loch_combo.BottomOffset        10)
        (loch_combo.LeftOffset          0)
        (loch_combo.RightOffset         0)
        (loch_spin.Columns              4)
        (loch_spin.AttachLeft           True)
        (loch_spin.MinColumns           4)
        (loch_spin.TopOffset            0)
        (loch_spin.BottomOffset         0)
        (loch_spin.LeftOffset           0)
        (loch_spin.RightOffset          0)
        (loch_spin.InputType            3)
        (loch_spin.Digits               2)
        (loch_hol_txt.Columns           8)
        (loch_hol_txt.AttachLeft        True)
        (loch_hol_txt.AttachRight       True)
        (loch_hol_txt.AttachTop         True)
        (loch_hol_txt.Alignment         0)
        (loch_hol_txt.TopOffset         5)
        (loch_hol_txt.BottomOffset      5)
        (loch_hol_txt.LeftOffset        0)
        (loch_hol_txt.RightOffset       0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     16)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1 1 1) (Cols 1)
                (Grid (Rows 0) (Cols 1 1)
                    loch_check
                    loch_txt
                )
                loch_hol_txt
                loch_combo
                loch_spin
            )
        )
    )
)

(Layout screwcb_layout
    (Components
        (CheckButton                    screwcb_check)
        (Label                          screwcb_txt)
        (OptionMenu                     screwcbreihe_combo)
        (SpinBox                        screwcb_dm_spin)
        (Label                          screwcb_x)
        (SpinBox                        screwcb_tiefe_spin)
        (Separator                      Separator33)
        (Label                          screwcb_hol_txt)
    )

    (Resources
        (screwcb_check.AttachLeft       True)
        (screwcb_check.AttachTop        True)
        (screwcb_check.TopOffset        8)
        (screwcb_check.BottomOffset     0)
        (screwcb_check.LeftOffset       0)
        (screwcb_check.RightOffset      4)
        (screwcb_check.FontStyle        8)
        (screwcb_txt.Label              "Side 1 - Counterbore")
        (screwcb_txt.Columns            8)
        (screwcb_txt.AttachLeft         True)
        (screwcb_txt.AttachTop          True)
        (screwcb_txt.Alignment          0)
        (screwcb_txt.TopOffset          10)
        (screwcb_txt.BottomOffset       0)
        (screwcb_txt.LeftOffset         0)
        (screwcb_txt.RightOffset        0)
        (screwcb_txt.FontStyle          8)
        (screwcbreihe_combo.Columns     0)
        (screwcbreihe_combo.MinColumns  0)
        (screwcbreihe_combo.TopOffset   5)
        (screwcbreihe_combo.BottomOffset 10)
        (screwcbreihe_combo.LeftOffset  0)
        (screwcbreihe_combo.RightOffset 0)
        (screwcb_dm_spin.Columns        4)
        (screwcb_dm_spin.AttachLeft     True)
        (screwcb_dm_spin.TopOffset      0)
        (screwcb_dm_spin.BottomOffset   0)
        (screwcb_dm_spin.LeftOffset     0)
        (screwcb_dm_spin.RightOffset    0)
        (screwcb_dm_spin.InputType      3)
        (screwcb_dm_spin.Digits         2)
        (screwcb_x.Label                "x")
        (screwcb_x.AttachLeft           True)
        (screwcb_x.TopOffset            0)
        (screwcb_x.BottomOffset         0)
        (screwcb_x.LeftOffset           6)
        (screwcb_x.RightOffset          6)
        (screwcb_tiefe_spin.Columns     4)
        (screwcb_tiefe_spin.AttachLeft  True)
        (screwcb_tiefe_spin.PopupMenu   "screwcb_popup")
        (screwcb_tiefe_spin.TopOffset   0)
        (screwcb_tiefe_spin.BottomOffset 0)
        (screwcb_tiefe_spin.LeftOffset  0)
        (screwcb_tiefe_spin.RightOffset 0)
        (screwcb_tiefe_spin.MinDouble   0.000000)
        (screwcb_tiefe_spin.InputType   3)
        (screwcb_tiefe_spin.Digits      2)
        (Separator33.TopOffset          10)
        (Separator33.BottomOffset       0)
        (Separator33.LeftOffset         0)
        (Separator33.RightOffset        0)
        (screwcb_hol_txt.Columns        8)
        (screwcb_hol_txt.AttachLeft     True)
        (screwcb_hol_txt.AttachTop      True)
        (screwcb_hol_txt.Alignment      0)
        (screwcb_hol_txt.TopOffset      3)
        (screwcb_hol_txt.BottomOffset   0)
        (screwcb_hol_txt.LeftOffset     1)
        (screwcb_hol_txt.RightOffset    0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 0 1 0) (Cols 1)
                Separator33
                (Grid (Rows 0) (Cols 0 1)
                    screwcb_check
                    (Grid (Rows 0 0) (Cols 1)
                        screwcb_txt
                        screwcb_hol_txt
                    )
                )
                screwcbreihe_combo
                (Grid (Rows 0) (Cols 0 0 1)
                    screwcb_dm_spin
                    screwcb_x
                    screwcb_tiefe_spin
                )
            )
        )
    )
)

(Layout screw_auto_udf_layout
    (Components
        (CheckButton                    screw_auto_udf_check)
        (Label                          screw_auto_udf_txt)
        (SpinBox                        screw_auto_udf_offset_spin)
        (Label                          screw_auto_udf_offset_txt)
        (Separator                      hidden1_sep)
    )

    (Resources
        (screw_auto_udf_check.AttachLeft True)
        (screw_auto_udf_check.AttachTop True)
        (screw_auto_udf_check.TopOffset 0)
        (screw_auto_udf_check.BottomOffset 0)
        (screw_auto_udf_check.LeftOffset 0)
        (screw_auto_udf_check.RightOffset 4)
        (screw_auto_udf_check.FontStyle 8)
        (screw_auto_udf_txt.Label       "Side 1 - Auto UDF")
        (screw_auto_udf_txt.Columns     8)
        (screw_auto_udf_txt.AttachLeft  True)
        (screw_auto_udf_txt.AttachTop   True)
        (screw_auto_udf_txt.Alignment   0)
        (screw_auto_udf_txt.TopOffset   2)
        (screw_auto_udf_txt.BottomOffset 0)
        (screw_auto_udf_txt.LeftOffset  0)
        (screw_auto_udf_txt.RightOffset 0)
        (screw_auto_udf_txt.FontStyle   8)
        (screw_auto_udf_offset_spin.Columns 4)
        (screw_auto_udf_offset_spin.AttachLeft True)
        (screw_auto_udf_offset_spin.PopupMenu "screwcb_popup")
        (screw_auto_udf_offset_spin.TopOffset 5)
        (screw_auto_udf_offset_spin.BottomOffset 0)
        (screw_auto_udf_offset_spin.LeftOffset 0)
        (screw_auto_udf_offset_spin.RightOffset 0)
        (screw_auto_udf_offset_spin.MinDouble 0.000000)
        (screw_auto_udf_offset_spin.InputType 3)
        (screw_auto_udf_offset_spin.Digits 2)
        (screw_auto_udf_offset_txt.Label "Offset")
        (screw_auto_udf_offset_txt.AttachLeft True)
        (screw_auto_udf_offset_txt.Alignment 0)
        (screw_auto_udf_offset_txt.TopOffset 5)
        (screw_auto_udf_offset_txt.BottomOffset 0)
        (screw_auto_udf_offset_txt.LeftOffset 6)
        (screw_auto_udf_offset_txt.RightOffset 10)
        (hidden1_sep.Visible            False)
        (hidden1_sep.TopOffset          0)
        (hidden1_sep.BottomOffset       0)
        (hidden1_sep.LeftOffset         0)
        (hidden1_sep.RightOffset        0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1 1) (Cols 1)
                (Grid (Rows 0) (Cols 0 1)
                    screw_auto_udf_check
                    screw_auto_udf_txt
                )
                hidden1_sep
                (Grid (Rows 1) (Cols 0 1)
                    screw_auto_udf_offset_txt
                    screw_auto_udf_offset_spin
                )
            )
        )
    )
)

(Layout nutcb_layout
    (Components
        (CheckButton                    nutcb_check)
        (OptionMenu                     nutcbreihe_combo)
        (SpinBox                        nutcb_dm_spin)
        (Label                          nutcb_x)
        (SpinBox                        nutcb_tiefe_spin)
        (Label                          nutcb_txt)
        (Separator                      Separator10)
        (Label                          nutcb_hol_txt)
    )

    (Resources
        (nutcb_check.AttachLeft         True)
        (nutcb_check.AttachTop          True)
        (nutcb_check.TopOffset          8)
        (nutcb_check.BottomOffset       0)
        (nutcb_check.LeftOffset         0)
        (nutcb_check.RightOffset        4)
        (nutcbreihe_combo.Columns       0)
        (nutcbreihe_combo.MinColumns    0)
        (nutcbreihe_combo.TopOffset     5)
        (nutcbreihe_combo.BottomOffset  10)
        (nutcbreihe_combo.LeftOffset    0)
        (nutcbreihe_combo.RightOffset   0)
        (nutcb_dm_spin.Columns          4)
        (nutcb_dm_spin.AttachLeft       True)
        (nutcb_dm_spin.TopOffset        0)
        (nutcb_dm_spin.BottomOffset     0)
        (nutcb_dm_spin.LeftOffset       0)
        (nutcb_dm_spin.RightOffset      0)
        (nutcb_dm_spin.InputType        3)
        (nutcb_dm_spin.Digits           2)
        (nutcb_x.Label                  "x")
        (nutcb_x.AttachLeft             True)
        (nutcb_x.TopOffset              0)
        (nutcb_x.BottomOffset           0)
        (nutcb_x.LeftOffset             6)
        (nutcb_x.RightOffset            6)
        (nutcb_tiefe_spin.Columns       4)
        (nutcb_tiefe_spin.AttachLeft    True)
        (nutcb_tiefe_spin.PopupMenu     "nutcb_popup")
        (nutcb_tiefe_spin.TopOffset     0)
        (nutcb_tiefe_spin.BottomOffset  0)
        (nutcb_tiefe_spin.LeftOffset    0)
        (nutcb_tiefe_spin.RightOffset   0)
        (nutcb_tiefe_spin.MinDouble     0.000000)
        (nutcb_tiefe_spin.InputType     3)
        (nutcb_tiefe_spin.Digits        2)
        (nutcb_txt.Label                "Side 2 - Counterbore")
        (nutcb_txt.Columns              8)
        (nutcb_txt.AttachLeft           True)
        (nutcb_txt.AttachTop            True)
        (nutcb_txt.Alignment            0)
        (nutcb_txt.TopOffset            10)
        (nutcb_txt.BottomOffset         0)
        (nutcb_txt.LeftOffset           0)
        (nutcb_txt.RightOffset          0)
        (nutcb_txt.FontStyle            8)
        (Separator10.TopOffset          0)
        (Separator10.BottomOffset       0)
        (Separator10.LeftOffset         0)
        (Separator10.RightOffset        0)
        (nutcb_hol_txt.Columns          8)
        (nutcb_hol_txt.AttachLeft       True)
        (nutcb_hol_txt.AttachTop        True)
        (nutcb_hol_txt.Alignment        0)
        (nutcb_hol_txt.TopOffset        3)
        (nutcb_hol_txt.BottomOffset     0)
        (nutcb_hol_txt.LeftOffset       0)
        (nutcb_hol_txt.RightOffset      0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 1 0 0) (Cols 1)
                Separator10
                (Grid (Rows 1) (Cols 0 1)
                    nutcb_check
                    (Grid (Rows 1 1) (Cols 1)
                        nutcb_txt
                        nutcb_hol_txt
                    )
                )
                nutcbreihe_combo
                (Grid (Rows 0) (Cols 0 0 1)
                    nutcb_dm_spin
                    nutcb_x
                    nutcb_tiefe_spin
                )
            )
        )
    )
)

(Layout nut_auto_udf_layout
    (Components
        (CheckButton                    nut_auto_udf_check)
        (Label                          nut_auto_udf_txt)
        (SpinBox                        nut_auto_udf_offset_spin)
        (Label                          nut_auto_udf_offset_txt)
        (Separator                      hidden2_sep)
    )

    (Resources
        (nut_auto_udf_check.AttachLeft  True)
        (nut_auto_udf_check.AttachTop   True)
        (nut_auto_udf_check.TopOffset   0)
        (nut_auto_udf_check.BottomOffset 0)
        (nut_auto_udf_check.LeftOffset  0)
        (nut_auto_udf_check.RightOffset 4)
        (nut_auto_udf_check.FontStyle   8)
        (nut_auto_udf_txt.Label         "Side 2 - Auto UDF")
        (nut_auto_udf_txt.Columns       8)
        (nut_auto_udf_txt.AttachLeft    True)
        (nut_auto_udf_txt.AttachTop     True)
        (nut_auto_udf_txt.Alignment     0)
        (nut_auto_udf_txt.TopOffset     2)
        (nut_auto_udf_txt.BottomOffset  0)
        (nut_auto_udf_txt.LeftOffset    0)
        (nut_auto_udf_txt.RightOffset   0)
        (nut_auto_udf_txt.FontStyle     8)
        (nut_auto_udf_offset_spin.Columns 4)
        (nut_auto_udf_offset_spin.AttachLeft True)
        (nut_auto_udf_offset_spin.PopupMenu "nutcb_popup")
        (nut_auto_udf_offset_spin.TopOffset 5)
        (nut_auto_udf_offset_spin.BottomOffset 0)
        (nut_auto_udf_offset_spin.LeftOffset 0)
        (nut_auto_udf_offset_spin.RightOffset 0)
        (nut_auto_udf_offset_spin.MinDouble 0.000000)
        (nut_auto_udf_offset_spin.InputType 3)
        (nut_auto_udf_offset_spin.Digits 2)
        (nut_auto_udf_offset_txt.Label  "Offset")
        (nut_auto_udf_offset_txt.AttachLeft True)
        (nut_auto_udf_offset_txt.Alignment 0)
        (nut_auto_udf_offset_txt.TopOffset 5)
        (nut_auto_udf_offset_txt.BottomOffset 0)
        (nut_auto_udf_offset_txt.LeftOffset 6)
        (nut_auto_udf_offset_txt.RightOffset 10)
        (hidden2_sep.Visible            False)
        (hidden2_sep.TopOffset          0)
        (hidden2_sep.BottomOffset       0)
        (hidden2_sep.LeftOffset         0)
        (hidden2_sep.RightOffset        0)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  10)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 0 1 1) (Cols 1)
                (Grid (Rows 0) (Cols 0 1)
                    nut_auto_udf_check
                    nut_auto_udf_txt
                )
                hidden2_sep
                (Grid (Rows 1) (Cols 0 1)
                    nut_auto_udf_offset_txt
                    nut_auto_udf_offset_spin
                )
            )
        )
    )
)

(Layout gewbohrtiefe_layout
    (Components
        (CheckButton                    durchgew_check)
        (CheckButton                    durchbohr_check)
        (CheckButton                    addthread_check)
        (SpinBox                        gewtiefe_spin)
        (SpinBox                        bohrtiefe_spin)
        (SpinBox                        bohrdm_spin)
        (Label                          gewtiefe_txt)
        (Label                          bohrtiefe_txt)
        (Label                          threadhole_txt)
        (Label                          bohrdm_txt)
        (Separator                      Separator1)
        (Label                          threadhole_hol_txt)
    )

    (Resources
        (durchgew_check.Label           "Through thread")
        (durchgew_check.AttachLeft      True)
        (durchgew_check.TopOffset       5)
        (durchgew_check.BottomOffset    10)
        (durchgew_check.LeftOffset      0)
        (durchgew_check.RightOffset     0)
        (durchbohr_check.Label          "Through hole")
        (durchbohr_check.AttachLeft     True)
        (durchbohr_check.TopOffset      0)
        (durchbohr_check.BottomOffset   10)
        (durchbohr_check.LeftOffset     0)
        (durchbohr_check.RightOffset    0)
        (addthread_check.Label          "With thread")
        (addthread_check.AttachLeft     True)
        (addthread_check.TopOffset      0)
        (addthread_check.BottomOffset   15)
        (addthread_check.LeftOffset     0)
        (addthread_check.RightOffset    0)
        (gewtiefe_spin.Columns          4)
        (gewtiefe_spin.AttachLeft       True)
        (gewtiefe_spin.MinColumns       4)
        (gewtiefe_spin.TopOffset        0)
        (gewtiefe_spin.BottomOffset     0)
        (gewtiefe_spin.LeftOffset       0)
        (gewtiefe_spin.RightOffset      0)
        (gewtiefe_spin.InputType        3)
        (gewtiefe_spin.Digits           2)
        (bohrtiefe_spin.Columns         4)
        (bohrtiefe_spin.AttachLeft      True)
        (bohrtiefe_spin.MinColumns      4)
        (bohrtiefe_spin.TopOffset       10)
        (bohrtiefe_spin.BottomOffset    10)
        (bohrtiefe_spin.LeftOffset      0)
        (bohrtiefe_spin.RightOffset     0)
        (bohrtiefe_spin.InputType       3)
        (bohrtiefe_spin.Digits          2)
        (bohrdm_spin.Columns            4)
        (bohrdm_spin.AttachLeft         True)
        (bohrdm_spin.MinColumns         4)
        (bohrdm_spin.TopOffset          0)
        (bohrdm_spin.BottomOffset       13)
        (bohrdm_spin.LeftOffset         0)
        (bohrdm_spin.RightOffset        0)
        (bohrdm_spin.InputType          3)
        (bohrdm_spin.Digits             2)
        (gewtiefe_txt.Label             "Thread depth")
        (gewtiefe_txt.AttachLeft        True)
        (gewtiefe_txt.Alignment         0)
        (gewtiefe_txt.TopOffset         0)
        (gewtiefe_txt.BottomOffset      0)
        (gewtiefe_txt.LeftOffset        10)
        (gewtiefe_txt.RightOffset       10)
        (bohrtiefe_txt.Label            "Drill depth")
        (bohrtiefe_txt.AttachLeft       True)
        (bohrtiefe_txt.Alignment        0)
        (bohrtiefe_txt.TopOffset        10)
        (bohrtiefe_txt.BottomOffset     10)
        (bohrtiefe_txt.LeftOffset       10)
        (bohrtiefe_txt.RightOffset      10)
        (threadhole_txt.Label           "Side 2 - Thread")
        (threadhole_txt.AttachLeft      True)
        (threadhole_txt.Alignment       0)
        (threadhole_txt.TopOffset       0)
        (threadhole_txt.BottomOffset    0)
        (threadhole_txt.LeftOffset      0)
        (threadhole_txt.RightOffset     0)
        (threadhole_txt.FontStyle       8)
        (bohrdm_txt.Label               "Drill diameter")
        (bohrdm_txt.AttachLeft          True)
        (bohrdm_txt.Alignment           0)
        (bohrdm_txt.TopOffset           0)
        (bohrdm_txt.BottomOffset        13)
        (bohrdm_txt.LeftOffset          10)
        (bohrdm_txt.RightOffset         10)
        (Separator1.TopOffset           0)
        (Separator1.BottomOffset        10)
        (Separator1.LeftOffset          0)
        (Separator1.RightOffset         0)
        (threadhole_hol_txt.Columns     7)
        (threadhole_hol_txt.AttachLeft  True)
        (threadhole_hol_txt.Alignment   0)
        (threadhole_hol_txt.TopOffset   5)
        (threadhole_hol_txt.BottomOffset 0)
        (threadhole_hol_txt.LeftOffset  0)
        (threadhole_hol_txt.RightOffset 10)
        (.Mapped                        False)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachTop                     True)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   10)
        (.Layout
            (Grid (Rows 1 1 1 1 1 1 0) (Cols 1)
                Separator1
                threadhole_txt
                threadhole_hol_txt
                durchgew_check
                durchbohr_check
                addthread_check
                (Grid (Rows 0 0 0) (Cols 1 0)
                    gewtiefe_txt
                    gewtiefe_spin
                    bohrtiefe_txt
                    bohrtiefe_spin
                    bohrdm_txt
                    bohrdm_spin
                )
            )
        )
    )
)

(Layout footer2_layout
    (Components
        (PushButton                     pb_Cancel2)
        (PushButton                     pb_OK2)
        (Separator                      Separator6)
    )

    (Resources
        (pb_Cancel2.Label               "Cancel")
        (pb_Cancel2.Columns             5)
        (pb_Cancel2.ButtonStyle         2)
        (pb_Cancel2.AttachRight         True)
        (pb_Cancel2.Alignment           1)
        (pb_Cancel2.TopOffset           10)
        (pb_Cancel2.BottomOffset        10)
        (pb_Cancel2.LeftOffset          0)
        (pb_Cancel2.RightOffset         10)
        (pb_OK2.Label                   "OK")
        (pb_OK2.Columns                 5)
        (pb_OK2.ButtonStyle             2)
        (pb_OK2.AttachRight             True)
        (pb_OK2.TopOffset               10)
        (pb_OK2.BottomOffset            10)
        (pb_OK2.LeftOffset              0)
        (pb_OK2.RightOffset             8)
        (Separator6.AttachBottom        True)
        (Separator6.TopOffset           0)
        (Separator6.BottomOffset        0)
        (Separator6.LeftOffset          0)
        (Separator6.RightOffset         0)
        (.AttachLeft                    True)
        (.AttachRight                   True)
        (.AttachBottom                  True)
        (.Alignment                     1)
        (.TopOffset                     0)
        (.BottomOffset                  0)
        (.LeftOffset                    0)
        (.RightOffset                   0)
        (.Layout
            (Grid (Rows 1 1) (Cols 1)
                Separator6
                (Grid (Rows 1) (Cols 1 0)
                    pb_OK2
                    pb_Cancel2
                )
            )
        )
    )
)

(MenuPane screwcb_popup
    (Components
        (Label                          screwcb_headline)
        (Separator                      screwcb_separator)
        (PushButton                     screwcb_maximum_button)
        (PushButton                     screwcb_select_button)
        (PushButton                     screwcb_measure_button)
    )

    (Resources
        (screwcb_headline.Label         "Set Screw Offset")
        (screwcb_headline.FontStyle     4)
        (screwcb_maximum_button.Label   "Maximum Value")
        (screwcb_select_button.Label    "Select")
        (screwcb_measure_button.Label   "Measure")
    )
)

(MenuPane nutcb_popup
    (Components
        (Label                          nutcb_headline)
        (Separator                      nutcb_separator)
        (PushButton                     nutcb_maximum_button)
        (PushButton                     nutcb_select_button)
        (PushButton                     nutcb_measure_button)
    )

    (Resources
        (nutcb_headline.Label           "Set Nut Offset")
        (nutcb_headline.FontStyle       4)
        (nutcb_maximum_button.Label     "Maximum Value")
        (nutcb_select_button.Label      "Select")
        (nutcb_measure_button.Label     "Measure")
    )
)
